### ISSUE TITLE
MapView Crashes (app close) 

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1029]
The MapView is crashing when it contains many lines after some zooming/panning actions.

Adding several points: Zoom/Pan, everything's fine.
Adding some lines between the points: Zoom/Pan: Memory increases, map lags, and finally the app closes. (See memory graphs attached below)

Maybe not reproducable on emulator, maybe needs a physical device for debugging. (Enable debugging and USB options; for seeing graph use Chrome devtools: https://docs.flutter.dev/development/tools/devtools/overview)

**Comment by Mike-3** [comment]
I have this exception in the emulator.

E/flutter (15029): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'double' is not a subtype of type 'Map<String, dynamic>'
E/flutter (15029): #0      restoreJsonMapViewData (package:gc_wizard/persistence/map_view/json_provider.dart:99:30)
E/flutter (15029): #1      MapViewPersistenceAdapter.setJsonMapViewData (package:gc_wizard/widgets/tools/coords/map_view/mapview_persistence_adapter.dart:259:22)
E/flutter (15029): #2      GCWMapViewState._buildEditButtons.<anonymous closure> (package:gc_wizard/widgets/tools/coords/map_view/gcw_mapview.dart:626:62)
E/flutter (15029): #3      GCWPasteButtonState._buildMenuItems.<anonymous closure>.<anonymous closure> (package:gc_wizard/widgets/common/gcw_paste_button.dart:76:32)
E/flutter (15029): #4      _rootRunUnary (dart:async/zone.dart:1434:47)

But I haven't gotten the app to crash in the emulator yet.

**Comment by S-Man42** [comment]
looks interesting

**Comment by Mike-3** [comment]
on web
Error: MissingPluginException(No implementation found for method checkPermissionStatus on channel flutter.baseflow.com/permissions/methods)
but no crash

**Comment by S-Man42** [comment]
No idea... do not find it...

**Comment by S-Man42** [comment]
Well it's quite easy:

1. Open Map
2. Version A: Create many points and lines inbetween. I mean really many many lines
2. Version B: Instead creating the lines manually, you can take the the sample file added [above](https://github.com/S-Man42/GCWizard/issues/1029#issuecomment-1119557136) -> Rename the .ZIP to .KML and import it to the Map ("Open" button).
4. Then pan and zoom the map a bit and it should crash the app.

**Comment by S-Man42** [comment]
Reproducable vids:

![way1](https://user-images.githubusercontent.com/16626063/172236419-c4722c4b-1a48-483d-8127-9013b2855d36.gif)
![way2](https://user-images.githubusercontent.com/16626063/172236884-ae547abd-ba7e-4c58-a023-53f0827229c5.gif)

**Comment by S-Man42** [comment]
Can anybody still reproduce this?

**Comment by S-Man42** [comment]
Not reported anymore.
