### ISSUE TITLE
Fundamental physical constants

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1038]
https://physics.nist.gov/cuu/Constants/index.html

idea for UI:
- DropDownButton "LIST_OF_CONSTANT_CLASSES" to choose a class of constants like e.g. Universal, Electromagnetic, Atomic & Nuclear, ...
- DropDownButton "LIST_OF_CONSTANTS_CLASS_UINVERSAL" to choose and display a specific constant
- OutPut: Abbrevation/Symbol, Numerical value, Standard uncertainty, Relative standard uncertainty, Concise form

Hence, we need three lists/maps.

The main one like
Map<String, Map<String, String> LIST_OF_CONSTANTS = {
'avogadro' : {'symbol' : 'NA', 
                     'name': 'natural_constants_constant_avogadro', // will be a parameter for i18n
                      'unit' : 'mol-1',
                      ' value' : '6.02214076  x 10E23 ',
                      'std_uncertain'' : 'natural_constants_constant_exact', // will be a parameter for i18n
                      'rel_uncertain': 'natural_constants_constant_exact',
                      'concise':  '6.02214076 x 10E23',},
'boltzmann' : ...,
'bohr_magneton'  : {'symbol' : 'NA', 
                     'name': 'natural_constants_constant_bohr_magneton', // will be a parameter for i18n
                      'unit' : 'J T-1',
                      ' value' : '9.274 010 0783 x 10-24 ',
                      'std_uncertain'' : '0.000 000 0028 x 10-24', // will be a parameter for i18n
                      'rel_uncertain': '3.0 x 10-10',
                      'concise':  '9.274 010 0783(28) x 10-24',},
...

**Comment by Birdy2404** [comment]
Hello @t-m-z,
what do you expect from my side?

**Comment by t-m-z** [comment]
You did a great job with ICAO - maybe you have an idea to create the main map with data
Map<String, Map<String, String> LIST_OF_CONSTANTS = {
'avogadro' : {'symbol' : 'NA',
'name': 'natural_constants_constant_avogadro', // will be a parameter for i18n
'unit' : 'mol-1',
' value' : '6.02214076 x 10E23 ',
'std_uncertain'' : 'natural_constants_constant_exact', // will be a parameter for i18n
'rel_uncertain': 'natural_constants_constant_exact',
'concise': '6.02214076 x 10E23',},
'boltzmann' : ...,
'bohr_magneton' : {'symbol' : 'NA',
'name': 'natural_constants_constant_bohr_magneton', // will be a parameter for i18n
'unit' : 'J T-1',
' value' : '9.274 010 0783 x 10-24 ',
'std_uncertain'' : '0.000 000 0028 x 10-24', // will be a parameter for i18n
'rel_uncertain': '3.0 x 10-10',
'concise': '9.274 010 0783(28) x 10-24',},

**Comment by Birdy2404** [comment]
We can make the code lines in Excel.
I just found a way to get an exported list as pdf. Do we have another posibiliy to get the list??

**Comment by t-m-z** [comment]
I have no clue - maybe copy the data from PDF to Notepad++ Editor and create a CSV-File which can be imported into Excel and then processed.
Or I write a tool, which reads the CSV and creates the map.

**Comment by S-Man42** [comment]
Guys, read the changelogs! :) It's already done in 2.2.0 ;)
