### ISSUE TITLE
symbol table mushrooms

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#1046]
GC6NKPJ
https://www.dafont.com/alien-mushrooms.font

**Comment by Birdy2404** [comment]
.../Exchange/Symboltabellen/alien_mushrooms
Ready for your implementation :-)

**Comment by S-Man42** [comment]
The mushroom font is only "Free for personal use". Therefore please add it to the License.md and the license widget.

How about the My little pony license?

**Comment by Birdy2404** [comment]
Little pony is completely free
