### ISSUE TITLE
Formel Solver: Import/Export data

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#106]
(from Andy)

When fixed #37, it is really simple to import/export the internal JSON data.

**Comment by capoaira** [comment]
https://forums.geocaching.com/GC/index.php?/topic/356382-geocache-wizard-gcw-der-nachfolger-von-gcc/&do=findComment&comment=5836994

> Eine ziemlich coole Funktion hingegen wäre es, wenn Owner von (längeren) Multis die Formeln vorbereitet zum Downlaod für den GCW anbieten könnten, so dass die Cacher wirklich nur noch unterwegs die Variablen eingeben und sich damit die nächste Station und später das Finale ausrechnen lassen könnten. Würde ich bei meinen Caches umsetzen, einmalige Arbeit für mich, mehrfacher Nutzen durch alle Cacher.
>
>So was ähnliches gab es früher schon einmal, ist dann aber eingestellt worden. Wie es hieß, weiß ich nicht mehr. 

Ist das mit diesem Issue gemeint? Würde mir auch gefallen :)

**Comment by S-Man42** [comment]
Yes, it is :)

**Comment by S-Man42** [comment]
Done in https://github.com/S-Man42/GCWizard/commit/9fa7d3d2a8c5de7ef73bbd604312150182de8450
