### ISSUE TITLE
Symbol Tables: Export Encryption

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#108]
(from Jonas via email)

Wenn encrypted the text, an export function would be nice.

Possible Issues:
- File Storage Permission required
- How to align the pictures. Some don't need gaps (e.g. birds on a wire), some need to be extremely aligned by a certain base line (tenctonese), ... Export as one-line (1x20) or most compact version (e.g. 4x5) or as-shown in GCWizard?

**Comment by t-m-z** [comment]
I agree to to implement an export function.
Regarding the issues, some thoughts:
- I don't think that gaps are necessary. Most of the symbols do not fill the square. So there are gaps.
- The alignment to a base line is important. This has to be considered when the pictures are created. Maybe the baseline has to added in a certain colour.
-  when I write complete sentences, I seperate the words with space. Then a question mark appears. Maybe the Letter 'space' should be represented by an empty square.
- Regarding the creation of the image I prefer a compact version.

**Comment by S-Man42** [comment]
Concerning:
Point 3) Well, that's not that easy. You could do this with symbol tables that do not include a special sign for the space. However, there are some tables which have an own sign for spaces (e.g. Semaphore). The question mark is just a place holder which signals that there's input that cannot be encoded correctly. In my personal opinion that's exactly the correct behaviour, since a space character may not be included into the set in is, therefore, an "invalid" character for that set. Nevertheless, I believe, for a possible export function this could be an exception an white spaces could be ignored from this rule by using an empty image instead.

Point 4) I believe, this depends on the use case. Many geocaching listings include just one line of symbols.

**Comment by S-Man42** [comment]
https://github.com/S-Man42/GCWizard/commit/e2137421b9dcfa5da2f57c58bef740ce1da10c7d
