### ISSUE TITLE
feature wish Koordinaten wie Multi Dekodierer

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#1082]
Eingabe von Koordinaten und Ausgabe als alle integrierten Formate
Somit sollte man sehen können ob es zu den gegebenen vermutlichen Koordinatenstrings aus dem Mystery eine Entsprechung gibt.

**Comment by Mike-3** [comment]
then same https://github.com/S-Man42/GCWizard/issues/988#issue-1181576628 ?
