### ISSUE TITLE
Map View: Show on Map: Open in external app

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#113]
(from HHL via gc.com forum)

Show on map should add the possibility to show coords and polygons on external apps.

Warning: Some map app may not support polygons (circles and geodetics)

**Comment by t-m-z** [comment]
I do not understand the need for that. There are a lot of apps showing ma data and probably every app uses its own internal format.
Maybe it is a better solution to create a gpx/kml/kmz or poi/ov2/...-file which could be imported.

**Comment by S-Man42** [comment]
Well, in my opinion, there are some use cases for, at least the coordinate export. You would be able to open the coordinate in, let's say, Google Maps, and could start the navigation immediately... Some map apps, like Locus, provide great additional features for working with point or provide other maps, such as offline maps.

Well, exporting polygons is something different. That would be just an additional gimmick, I think :D

**Comment by t-m-z** [comment]
I agree to the need for an export of coordinates to navigate to them. But we should keep an eye on complexity. Maybe export to google maps, Locus and a few other well known apps for navigation should be sufficient.
