### ISSUE TITLE
Web: Issues with scrolling

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#1206]
- test for scroll with arrow keys on web version

- importent test features:
ToolLists
ImageColorCorrections
MapView
wherigo_analyse
symbol_tables (encryption/decryption)
symbol_tables_examples
symbol_replacer
hex_viewer
About
changelog

**Comment by S-Man42** [comment]
Current issues in web:
- Scrolling with arrow keys in List Views (such as main view tool lists)
- Scrolling with "touch gesture" panning on tools with "SingeScroll...dingens" widget
