### ISSUE TITLE
Enhance WASD with diagonal directions

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1208]
@t-m-z What do you think? I saw something like this a few times, e.g. https://coord.info/GC9K0X7

**Comment by t-m-z** [comment]
In the origin there is only up, down, right lef tand no diagonal movement.

However, we could enhance the tool 

 

 

Von: MLorenz42 ***@***.***> 
Gesendet: Saturday, 17 December 2022 11:27
An: S-Man42/GCWizard ***@***.***>
Cc: Thomas ***@***.***>; Mention ***@***.***>
Betreff: [S-Man42/GCWizard] Enhance WASD with diagonal directions (Issue #1208)

 

@t-m-z <https://github.com/t-m-z>  What do you think. I saw something like this a few times, e.g. https://coord.info/GC9K0X7

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/208308490-c9b07148-eeae-4ef8-9f5f-80140d6de824.png)

**Comment by S-Man42** [comment]
🤟
