### ISSUE TITLE
Bug: Symbol Replacer internet search can not bring up images from geocaching.Com url's

### ISSUE THREAD

**Issue by jamesanderson16** [S-Man42/GCWizard#1210]
Hi,

After trying on app as well as PC, if you want to use the symbol replacer, it doesn't let you use Amazon server web link images (which is what geocaching.com uses)

Can this be investigated please,

Thanks

James0116

**Comment by S-Man42** [comment]
Hi, unfortunately we have a problem with loading files directly from an url in the web view in general.

https://github.com/S-Man42/GCWizard/issues/983

That's something we are investigating at the moment. That's one of the main reasons for the disclaimer at the web view start.
