### ISSUE TITLE
Refactor File save/load

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1215]
Currently all bytes are converted to Uint8. This fits for every byte-based format (images, sounds, ...) and ascii-based texts. But it creates issues when storing text with special characters like Korean:

- Storing settings
- Storing GPX/KML with Korean titles
- ...

So, here we need proper UTF-8 encoding, which is currently not done.

**Comment by Mike-3** [comment]
use saveStringToFile and readStringFromFile for strings.
