### ISSUE TITLE
Trithemius/Ave Maria Code/Polygraphia

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1230]
https://en.wikipedia.org/wiki/Polygraphia_%28book%29?wprov=sfla1  (The Symbol Table, are there more in the book?)

The book:
https://books.google.de/books?id=fQdCAAAAcAAJ&pg=PP1&redir_esc=y#v=onepage&q&f=false

Ave Maria Code:
https://practice.nationalcybercup.org/cryptography/avemaria

In the text, they mention a ß which is not in the table. Can we find the original reference for completeness?

**Comment by t-m-z** [comment]
Nice ideas.

Regarding the szett the text says "The Latin letter ß (Eszett) does not exist in the English Alphabet, so we will omit it."

Sent from MailDroid

-----Original Message-----
From: MLorenz42 ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Di., 27 Dez. 2022 18:21
Subject: [S-Man42/GCWizard] Trithemius/Ave Maria Code/Polygraphia (Issue #1230)

https://en.wikipedia.org/wiki/Polygraphia_%28book%29?wprov=sfla1  (The Symbol Table, are there more in the book?)

The book:
https://books.google.de/books?id=fQdCAAAAcAAJ&pg=PP1&redir_esc=y#v=onepage&q&f=false

Ave Maria Code:
https://practice.nationalcybercup.org/cryptography/avemaria

In the text, they mention a ß which is not in the table. Can we find the original reference for completeness? 

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/issues/1230

**Comment by t-m-z** [comment]
The symbol table is already incorporated in the GC Wizard

Sent from MailDroid

-----Original Message-----
From: MLorenz42 ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Di., 27 Dez. 2022 18:21
Subject: [S-Man42/GCWizard] Trithemius/Ave Maria Code/Polygraphia (Issue #1230)

https://en.wikipedia.org/wiki/Polygraphia_%28book%29?wprov=sfla1  (The Symbol Table, are there more in the book?)

The book:
https://books.google.de/books?id=fQdCAAAAcAAJ&pg=PP1&redir_esc=y#v=onepage&q&f=false

Ave Maria Code:
https://practice.nationalcybercup.org/cryptography/avemaria

In the text, they mention a ß which is not in the table. Can we find the original reference for completeness? 

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/issues/1230

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209708794-f9da048a-4ddf-4ba5-abc5-34bbdcbd7c54.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209708845-e22b5abf-e150-4597-bef6-acd460212c2e.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209708895-c7cad299-47e2-4033-8537-116dabebf902.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209708950-40c9cccd-e80c-46d6-bf50-a64b43c1d329.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209709193-a884a735-7037-4f3f-bc5b-e0bbd7e757d8.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209709227-1454d221-86c6-463b-92d4-a44b3106f2c6.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209709283-8c2407de-ee3a-4196-b698-4009cc447674.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209709312-395aaced-7e1a-4265-8ab2-d318f1348c64.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209709412-4647749e-c080-4b30-838c-e73d894b4888.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209709472-806fc352-9c3c-4e8e-b25c-6c29586be3d2.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209709541-1b83b651-348a-48cd-8701-a708de6f189b.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/209709557-7c6cfc79-7f8d-4547-a74d-38ba43885e65.png)

**Comment by t-m-z** [comment]
Regarding the Ave Maria Code:
The tables start at page 31 and end at page 378
 => there are 347 pages with two colums each
 => up to 700 words per letter
 => the description of the code is lacking some details

Another code starts at page 382 up to page 425
