### ISSUE TITLE
Blue Monday Code

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1238]
https://kryptografie.de/kryptografie/chiffre/blue-monday.htm

**Comment by S-Man42** [comment]
https://coord.info/GCA28PC

**Comment by t-m-z** [comment]
https://en.wikipedia.org/wiki/Blue_Monday_(New_Order_song)#:~:text=%22Blue%20Monday%22%20was%20composed%20on%20a%20prototype-level%20homebrew,It%20contains%20a%20basic%20chord%20progression%20of%20Dm%E2%80%93F%E2%80%93C%E2%80%93Dm%E2%80%93G%E2%80%93C.

**Comment by t-m-z** [comment]
https://archive.ph/20130216234810/http://www.uponpaper.com/features/deciphered-peter-saville/

**Comment by Birdy2404** [comment]
I will take care for it

**Comment by Birdy2404** [comment]
[blue_monday.zip](https://github.com/S-Man42/GCWizard/files/10406148/blue_monday.zip)
[_Codeschnipsel.txt](https://github.com/S-Man42/GCWizard/files/10406149/_Codeschnipsel.txt)
Have fun implementing :-)

**Comment by Birdy2404** [comment]
Exchange/Symboltabellen/Blue_Monday
