### ISSUE TITLE
Optimize Navajo

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1243]
WOL-LA-CHEE NO-DA-IH CHUO BE-TKAH CHINDI DZEH GAH BE-TKAH DIBEH BI-SO-DIH NO-DA-IH AH-LOSZ BE-TKAH LHA-CHA-EH AH-JAH DIBEH BE-TKAH DAH-NES-TSA A-KHA D-AH AH-NAH A-CHIN BE-TKAH NA-AS-TSO-SI TSE-NILL TSAH TSAH AH-NAH DIBEH BE-TKAH AH-NAH DAH-NES-TSA TSE-GHA BE-LA-SANA AH-NAH DIBEH-YAZZIE KLESH D-AH BE-TKAH CHA YE-HES TSAH GLOE-IH AH-JAH A-CHI DIBEH BE-TKAH BE-LA-SANA MOASI LIN THAN-ZIE DA-AHL-ZHIN

(Some Letters not recognized)

TSE-GAH for H

Maybe others missing as well?

**Comment by t-m-z** [comment]
I do not understand the problem. I have incorporated the official code talker dictionary.
Unknown Navajo words are decoded with unknown symbol.
BE-TKAH is such an unknown word. Hence it is decoded as unknown.
For further work it would be helpful 
1. to decide how to act with unknown words: print a space or print unknown_symbol 
2. to provide your source of Navajo-Words
3. to provide the GC-Code

Regarding BE-TKAH which means BETWEEN can be decoded as B or space
Regarding TSE-GAH which means HAIR can be decoded as H.
Another Example: "Das Navajo-Wort Tkin stand für den Buchstaben "i", weil seine Übersetzung im Englischen "Ice" lautet, was mit "i" beginnt. Das gilt allerdings auch für die Wörter Ye-Hes ("itch", jucken) und A-Chi ("intestine", Darm), die daher ebenfalls für "i" standen. " See https://www.spiegel.de/geschichte/geheimnachrichten-im-zweiten-weltkrieg-der-code-der-besser-als-die-enigma-war-a-108e69df-7686-4657-a941-2fb7d6241a29

Are you really intend to incorporate the whole Navajo Language e.g. https://glosbe.com/nv

**Comment by t-m-z** [comment]
I suggest we add Navajo-words case by case

**Comment by t-m-z** [comment]
Conclusion:
- Typos can occur and should be result in <?>
- I will add DA-AHL-ZHIN as '.'
- I will add BE-TKAH as ' '

**Comment by S-Man42** [comment]
Yes, as I updated the post only a few minutes after creating: I only was missing TSE-GAH. Nothing else. Only a check whether it is really missing and if something else was forgotten. :)

**Comment by t-m-z** [comment]
TSE-GAH is not missing - it was a typo in your example

**Comment by t-m-z** [comment]
if  something is missing then it is an invention from geocachers

**Comment by S-Man42** [comment]
Ah, ok, check. Then this can be closed.
