### ISSUE TITLE
Symbol code proposal: Three-Squares Code / Drei-Quadrate-Code

### ISSUE THREAD

**Issue by radlerandi** [S-Man42/GCWizard#128]
http://kryptografie.de/kryptografie/chiffre/three-squares.htm#:~:text=Der%20Three%20Squares%20(dt.,dann%20f%C3%BCr%20den%20entsprechenden%20Buchstaben.

**Comment by radlerandi** [comment]
ah ok. hab den Blogpost gelesen und werde den Request erstmal schließen. Ggf. treibe ich ja eine andere Quelle dafür auf und liefere dann die Bildchen auch gleich im gewünschten Format mit. closed.

**Comment by capoaira** [comment]
https://www.geocachingtoolbox.com/index.php?lang=de&page=codeTables&id=threeSquaresCipher

**Comment by radlerandi** [comment]
danke! kommt auf meine Liste, sammel erstmal noch ein paar bzw. hab auch grade (eigentlich bis September) nicht die Zeit fürs Schnibbeln. ;-)
