### ISSUE TITLE
Add Bacon Cipher V2 (Destinct version)

### ISSUE THREAD

**Issue by jamesanderson16** [S-Man42/GCWizard#1282]
Hi,

I just tried to solve a puzzle with the bacon cipher solver which I couldn't do as it was a different version of bacon cipher (bacon cipher V2)

Could this be added to the bacon cipher decoder please (see link for example of 2 bacon cipher decoder)

[https://www.geocachingtoolbox.com/index.php?lang=en&page=baconianCipher]()

Thanks

James A

**Comment by S-Man42** [comment]
I think, that will be possible!

Currently we are completely refactoring the tool, so a new version may take a while. But we will add it afterward, I surely believe.

**Comment by jamesanderson16** [comment]
Thanks
