### ISSUE TITLE
Formula Resolver / WebSite

### ISSUE THREAD

**Issue by mahoplus** [S-Man42/GCWizard#129]
to add a new formula group doesn't work - to click on the plus-sign results no action

**Comment by capoaira** [comment]
Yes, the Formula Solver does not work in the web view: #37 
If you download the app from the google play store or from the apple app store, the Formula Solver will work.

**Comment by mahoplus** [comment]
ok, thanks for the advice. I use the solver under android and it works well, but editing complicated formula is not confortable on a mobile device

**Comment by S-Man42** [comment]
Hi,

currently I am working on this. This demands a complete internal rebuild of the formula solver, but the goal is to get it worked at the web view. Then it will be also possible to export/import the formulas.

#37 #106

**Comment by S-Man42** [comment]
Duplicate of #37
