### ISSUE TITLE
Rabbit Code Bug

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1296]
(from Team chanride via WhatsApp)

https://coord.info/GCA54TP

Hallo,

schau mal,
Ich hatte das erste Mal Rabbit Chiffre und es hat etwas gedauert, bis ich das dekodieren konnte.
Letztendlich hat es leider nur auf kryptografie.de funktioniert.

Beim GCWizard konnte ich am Handy nicht einmal die Zeichenkette mittels kopieren einfügen. Es hat einfach nicht funktioniert (habe das S22 Ultra) - mir wurde alles weiß angezeigt.

**Comment by S-Man42** [comment]
Text: FCD8073FFA61FB0DB88CE39360171962E4FCC2C26CE5
Schlüssel: Karotten

**Comment by S-Man42** [comment]
1. The code works with krypto.de, so seems to be valid. 

2. NullPointer (in 2.3.0) when pasting the Text from internal Clipboard: Internal clipboard settings looks as follows:

`[{"text":"FCD8073FFA61FB0DB88CE39360171962E4FCC2C26CE5","created":"1678556924272"}]`

**Comment by Mike-3** [comment]
The problem is that the hex string is not automatically broken down into individual numbers. But I can change that.
If hex is recognized and no space is present, the text is broken into groups of two.

**Comment by S-Man42** [comment]
Yes, you can NEVER EVER expect any formatting. Case-sensitive, line breaks, spaces. The input will always be in a way you don't expect ;) Please check for binary as well.

However, you are aware of this function? https://github.com/S-Man42/GCWizard/blob/3562045153adab43c99b92b7fa2afc620aef0b5b/lib/utils/string_utils.dart#L68 Seems, you gonna need it here.

What me confused too, is the paste thing. It's one thing that it doesnt calculate the result correctly because of the formatting issue, but why does it break completely when inserting the text from the clipboard in the app, but NOT in the web version?

**Comment by Mike-3** [comment]
This function is now used.
It works with the tests. Have yet to test it in the widget.

**Comment by Mike-3** [comment]
I believe this issue can be closed. There is an associated test that is passed successfully.
