### ISSUE TITLE
Web-Version / language

### ISSUE THREAD

**Issue by mahoplus** [S-Man42/GCWizard#130]
in Firefox (prefered browser, actual version 78.0.1) the application appears in english language
on same notebook in newest chrome in german language

on which isssue is this depending?

**Comment by S-Man42** [comment]
Actually I have no idea :D The apps request the internal system language. I guess, this is the same with the browser's system. Isn't it?

**Comment by AndyPuma** [comment]
Mit Safari auf dem iPad  ist die Weboberfläche deutsch. :)

MLorenz42 <notifications@github.com> schrieb am So., 5. Juli 2020, 18:21:

**Comment by mahoplus** [comment]
heute noch mal mit verschiedenen Devices und Browsern getestet:
Notebook (W10 2004)
Firefox heute in deutsch
chrome in english
opera in english
edge in deutsch

Tablett (andoid)
firefox in english
interner browser in deutsch

Samsung S8 (android)
firefox in deutsch
interner browser in english

**Comment by capoaira** [comment]
Perhaps it makes sense to add the language setting to the main settings.
If languages are added, the language used can be changed later. Or does the app check the system language every time it is opened?

**Comment by S-Man42** [comment]
The app checks the system language, even if the app is open and you'll change the language. But it is not clear to me, how the web view works or how the different browsers provide the language information...

**Comment by S-Man42** [comment]
Close this because I don't even know what to do here. Please feel free to reopen it if there are any issues :)
