### ISSUE TITLE
variable coordinates / android device

### ISSUE THREAD

**Issue by mahoplus** [S-Man42/GCWizard#131]
is it possible to store the last input? with ending the app the last input ist lost!
is it possible to get here the same procedure like the formula solver with groups?
is it possible to make the variables editable? Now the only way to edit is to delete and subsequently to add the same variable with other values

**Comment by S-Man42** [comment]
Actually, one of the goal of rewriting the formula solver's internal storage routines is to port it also for this. Currently, I am not sure if it would make it to the upcoming version 1.0.0 but it is planned to get it worked.

**Comment by S-Man42** [comment]
Everything done in https://github.com/S-Man42/GCWizard/commit/2e3cec1af63e4f6d4fdde0c88b4af61f1d346c7d
