### ISSUE TITLE
Kaktovik Numerals

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#1332]
https://www.golem.de/news/mathematik-innovatives-inuit-zahlensystem-wurde-digitalisiert-2304-173571.html

- [ ] Reallisation like babylonian numbers?
- [x] Symbol table preparation
- [ ] Symbol table implementation
- [ ] numeral words

**Comment by t-m-z** [comment]
Of Course and additionally a Symbol table

**Comment by Birdy2404** [comment]
And numeral words are available here:
https://www.adn.com/alaska-life/2022/11/06/numerals-invented-by-kaktovik-students-can-now-be-used-digitally/
0-59:
https://www.adn.com/resizer/whzsLjwgHOaQvJ4P0xIZjQeqRbQ=/1440x0/filters:format(jpg):quality(70)/cloudfront-us-east-1.images.arcpublishing.com/adn/JEVHLTM6FFFPLMPNZBFFXEZLEE.jpg

**Comment by Birdy2404** [comment]
@Mike-3 : Symbols are stored at /Exchange/Symboltabellen/Kaktovik
