### ISSUE TITLE
Stenografie symbols

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1354]
https://www.geocaching.com/geocache/GC6BTNM_der-ungewohnliche-arbeitstag-der-hannelore-hinz

http://www.stenoweb.de/Stenoweb/Lehr-_und_Unterrichtsmaterial_files/Stenografisches%20Wo%CC%88rterbuch%20DEK%20Verkehrsschrift%202020-08-06.pdf
eins zwei drei vier fünf sechs sieben acht neun null
zehn zwanzig dreißig vierzig fünfzig sechzig siebzig achtzig neunzig
einhundert
tausend
grad punkt komma strich
nördlich nord norden
südlich süd süden
östlich ost osten
westlich west westen

**Comment by Birdy2404** [comment]
The following Symbols are created and stored at the Exchange. Please don't forget the special mappings.

eins zwei drei vier fünf sechs sieben acht neun null --> done
zehn zwanzig dreißig vierzig fünfzig sechzig siebzig achtzig neunzig --> only 10 available
einhundert --> done
tausend --> Tausende
grad punkt komma strich --> Grad, Punkt, Komma, Minus
nördlich nord norden --> nördlich Norden
südlich süd süden --> done
östlich ost osten --> done
westlich west westen --> done
