### ISSUE TITLE
Logical solver

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1358]
as for example
http://www.jsingler.de/apps/logikloeser/?language=de#(at:s,items:!(!(Steffi,George,Barack,Carla,Roger),!(Cambridge,Obama,Graf,Federer,Bruni),!('1969','2013','1961','1967','1981'),!(CH,UK,D,USA,F)),ms:t,n:!(),nc:4,ni:5,p:!(),v:0)

**Comment by S-Man42** [comment]
Same problem as #243 I don't believe it's the logic which is complicated, but the input widget. (Because of the many columns and rows which can grow exponentially...)
