### ISSUE TITLE
Feature Request - phonetic alphabet

### ISSUE THREAD

**Issue by jamesanderson16** [S-Man42/GCWizard#1359]
Hi,

Could a phonetic alphabet decoder be made in the future please 😊

Thanks

James A

**Comment by t-m-z** [comment]
Hi James,

This is an interesting idea. Do have an example Geocache to show how this decoder should work?

Kind regards
Thomas

Sent from MailDroid

-----Original Message-----
From: jamesanderson16 ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Subscribed ***@***.***>
Sent: So., 07 Mai 2023 9:29
Subject: [S-Man42/GCWizard] Feature Request (Issue #1359)

Hi,

Could a phonetic alphabet decoder be made in the future please 😊

Thanks

James A

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/issues/1359

**Comment by jamesanderson16** [comment]
GC9R4YE

**Comment by t-m-z** [comment]
Okay. Now it is clear we are not talking about phonetic and pronunciation but spelling.

I am already working on a tool to list different spelling alphabets.

The next step will be a decrypt/encrypt tool.

Regards
Thomas


Sent from MailDroid

-----Original Message-----
