### ISSUE TITLE
Feature update - Symbol Replacer

### ISSUE THREAD

**Issue by jamesanderson16** [S-Man42/GCWizard#1360]
Hi,

Could the symbol replacer have the possibility to open the image library or the file library (which is an option on iPhones),

Thanks

James A

**Comment by jamesanderson16** [comment]
![image](https://user-images.githubusercontent.com/55370705/236664166-0c754fe3-ff01-4813-b0a2-af81b05c050e.jpeg)

**Comment by S-Man42** [comment]
Sorry, I completely missed this one. I will have a look at this. However, I cannot promise this because on iOS such things are usually complicated and our skills on this system are rather low...
