### ISSUE TITLE
Anpassen der Readme.md

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#137]
Ich habe nach der Anleitung alles installiert und beim compilieren eine Fehlermeldung zu einer fehlenden Lizenz erhalten. Ursache war: es fehlte im SDK Manager der API-Level 28. 
Bitte mal prüfen und ggf. um den Hinweis ergänzen, dass im Android Studio über Tools - SDK Manager - System Settings - Android SDK Android 9.0 zu installieren ist.

**Comment by S-Man42** [comment]
Done in #139
