### ISSUE TITLE
Geohashing

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1373]
(via mail by mic@)

https://geohashing.site/geohashing/Main_Page

**Comment by Mike-3** [comment]
Example https://coord.info/GC5CNKQ

**Comment by Mike-3** [comment]
https://github.com/lukekarrys/geohash-coordinates/tree/master
https://github.com/CaptainSpam/geohashdroid

**Comment by S-Man42** [comment]
we really dont need an external lib for that. it's a quite simple algorithm. so we can do this really quickly. by ourselves

**Comment by S-Man42** [comment]
ah I missed the Dow Jones component...

**Comment by Mike-3** [comment]
![grafik](https://github.com/S-Man42/GCWizard/assets/70719484/939fc105-6e44-46bf-80a5-e6559fca9af3)
![grafik](https://github.com/S-Man42/GCWizard/assets/70719484/e7b88cb4-e055-4102-891a-b4ceb1dc4a78)
