### ISSUE TITLE
Feature Symbol Warhammer 40.000 Zwergenrunen

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1374]
https://whfb-de.lexicanum.com/wiki/Klinkarhun

**Comment by t-m-z** [comment]
![image](https://github.com/S-Man42/GCWizard/assets/2946628/c54a4673-64b2-44a2-aa62-9cf5ddda7d75)

vier  neun  zwei  sieben  sieben  acht  neun  null  null  sechs  drei  sieben  f-nf  zwei  drei

**Comment by S-Man42** [comment]
Linked table and shown image are not the same, aren't they?

Please always not forget to check the rights before adding symbol tables from commercial franchises

**Comment by t-m-z** [comment]
Yes the image is from https://www.geocaching.com/geocache/GC9RRVR

It seems to be related to Ezekyle Abaddon from Warhammer. While searching for the symbols I found the runes.

Of course will the rights be checked

**Comment by Birdy2404** [comment]
Couldn't find free sources for both fonts.
@t-m-z, if you don't have a free source, I would recommend to close the ticked unsolved.

**Comment by t-m-z** [comment]
Check. I wasn't successful either 

Sent from MailDroid

-----Original Message-----
