### ISSUE TITLE
Cannot open this file

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1442]
(tried as "load from url") 

https://img.geocaching.cf/cache/1284445f-11e8-4e85-8a8c-36a53f21809e.jpg

In old version it worked (tested in Exif, HiddenData, HexViewer)

In new version it could not be loaded (testes in HiddenData, HexViewer)

Although it seems to be a very special file (https://www.geoclub.de/forum/t/gc878d7-global-geocaching-k%C3%B6ln-global-geocaching-series.82611/) it should be loaded nonetheless. At least in the HexViewer, which should open simply everything.

**Comment by Mike-3** [comment]
Problem only with hex viewer. It was not a specific file problem.
