### ISSUE TITLE
Berber alphabet

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1444]
Today at Die Sendung mit der Maus. I am sure all. Geocachers watch the Maus and now many Berber mysts will pop up ;)

https://en.wikipedia.org/wiki/Tifinagh?wprov=sfla1

**Comment by Birdy2404** [comment]
/Exchange/Symboltabellen/Berber

As some of the letters are special character (Gamma, Epsilon, K_dot), I didn't compress them and kept an underscore at the beginning of thos letters.

**Comment by Mike-3** [comment]
Sorry, only now saw that you wanted to do this

**Comment by t-m-z** [comment]
done by Mark
