### ISSUE TITLE
Alien language

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1461]
https://www.youtube.com/watch?v=di3p2YN_jXc

**Comment by Birdy2404** [comment]
At the moment I can't find a original symbol table. I have requested it from Karin. Let's see, if I get a response.

**Comment by Birdy2404** [comment]
http://kryptografie.de/kryptografie/chiffre/zentradi.htm

**Comment by Birdy2404** [comment]
I like the new TTF-conversion :-)
/Exchange/Symboltabellen/Zentraedi

**Comment by Mike-3** [comment]
Die gleichen Symbole haben wir schoon unter Zentradi. Sieht nur mit dem Font sauberer aus.
Aber was ist die richtige Schreibweise ?

**Comment by Mike-3** [comment]
Ok
