### ISSUE TITLE
new Category: Miscelleanous

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1462]
- Zodiac
- GCW Script
- ...

**Comment by S-Man42** [comment]
Hmm nee, bin ich irgendwie nicht glücklich mit.
Zodiac ist zwar intern ne eigene Kategoire, weil es nun mal keine Wissenschaft ist. Aber ne komplett eigene Kategorie dafür aufzumachen lohnt nicht.

Und willst du Script wirklich unter "sonstiges" reinhauen? Zusammen mit Astrologie? Auch iwie doof.

**Comment by t-m-z** [comment]
Stimmt beides -

Aber
- Ich habe die Tierkreiszeichen nur durch Zufall im Onlinemanual entdeckt - nicht in der App.
- zu viele Kategorien machen die Startseite unübersichtlich

Oder ich packe GCWScript in Wissenschaft und Technik 


Sent from MailDroid

-----Original Message-----
