### ISSUE TITLE
Exception at decodeBase16('A')

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1499]
Exception bei decodeBase16('A'), es werden mindestens 2 Zeichen erwartet, es gibt keine Base Tests

**Comment by t-m-z** [comment]
???

**Comment by S-Man42** [comment]
was a bug finding by Mike from the GCW3 Test Sheet

**Comment by t-m-z** [comment]
Interesting - I cannot reproduce it.

Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
Please check together with @Mike-3 and close if not reproducable anymore.

**Comment by Mike-3** [comment]
If I remember correctly, this is where the exception was thrown. 
`input.substring(i, i + 2)`
The string was just 1 character long.

**Comment by t-m-z** [comment]
thats right - the exception will be thrown for every string with an odd length

a quite simple workaround would be a test for the input length: if (input.isEmpty || input.length % 2 != 0) return '';
