### ISSUE TITLE
enhancement rotation

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1542]
allow a set of indizes to rotate a given text charcterwise

http://abload.de/img/tapetenqk3u.jpg

from

 https://www.geocaching.com/geocache/GC71W08_die-rache-des-puzzlemorders-lp

**Comment by S-Man42** [comment]
Is this not simple "substitution" tool? Or automatic substitutiom breaker?

**Comment by t-m-z** [comment]
as already discussed it is a vigenere encryption
