### ISSUE TITLE
Centroid (Arithmetic Mean) Not Working

### ISSUE THREAD

**Issue by danbrust** [S-Man42/GCWizard#1564]
The submit button doesn't seem to be working when using this tool. I've tried on both Android and the website. If I fill in 3 sets of coordinates and click Submit, nothing happens. If I leave one of the 3 blank, then it DOES work (just way off as I'm guessing it is averaging in the blanks, too). Seems like there might be some validation routine that is stopping the tool from running?

**Comment by S-Man42** [comment]
Hi, thanks for your report.

However, I cannot reproduce this behaviour. May you give us more details?

iOS or Android or Web?
The data you tried?
Maybe a screenshot?

**Comment by danbrust** [comment]
I have the same issue on both the Android version and in Firefox on a Windows PC.

1. Go to the Centroid tool.
2. Increase the # of coordinates to 3.
3. Use DMM: DD MM.MMM format for all 3.
4. Enter coordinates for each.
5. Click Submit --> Nothing happens.
6. Adjust the number of coordinates to 2, then back to 3.
7. Leave the 3rd set blank.
8. Click Submit --> It works, but must be factoring in the 3rd blank set.
9. Fill in coordinates for the 3rd set.
10. Click Submit --> Nothing happens.

**Comment by S-Man42** [comment]
Strange, for me it works perfectly fine on both Android and web.

It would lobe to see your actual inputs and a screenshot if possible.

**Comment by S-Man42** [comment]
Hi @danbrust

it's strange. The entire team was trying to reproduce the described behaviour on several systems. We are absolutly not able to do that. It works fine everywhere, smartphones with different systems and version, different browser, emulators and so on.

So from our point of view, we need much more input from you:

What is your concrete data you are inputting?
What is you used GCW version? (Click on the logo in the top left corner -> About)
Please send us a screenshot of what you entered.

**Comment by danbrust** [comment]
I went and found a random GC and plugged in its coordinates, and still had the same issue. See the attached screenshots from the Android app.

The submit button does nothing when all 3 are filled in. If I clear out the third, then it at least calculates. I should note that I didn't have this problem before, it only started after one of the most recent updates.

![Screenshot_20231222_065529](https://github.com/S-Man42/GCWizard/assets/3865576/bc3d1c2d-dafd-4fc1-9b1c-adffe4dc433c)
![Screenshot_20231222_065554](https://github.com/S-Man42/GCWizard/assets/3865576/ebbdac64-3b0f-4135-b0b6-cfa079c50a48)
![Screenshot_20231222_065627](https://github.com/S-Man42/GCWizard/assets/3865576/dae486c1-b9c9-4f37-b006-a01698e44304)

**Comment by S-Man42** [comment]
Hm, I dont know why, but I got some strange behaviour as well after some playing around.

How do you enter your coordinates?

By typing, "own location" button or by pasting from clipboard?

**Comment by danbrust** [comment]
I usually paste from c:geo, but in this last example, I manually typed in the first set. I then used the copy and paste buttons to paste to 2 and 3, then manually tweaked a single number.

**Comment by S-Man42** [comment]
Yes... I guess it has something to do with the paste entering... That's when I get problems too. I will dive into it the next days.

**Comment by S-Man42** [comment]
@danbrust Hi, I hope I fixed it. As a bug reporter you gain a place in the testers list. How do you want to be named?
