### ISSUE TITLE
Feature Request: Reference to sub-formulars by Name

### ISSUE THREAD

**Issue by UJstr** [S-Man42/GCWizard#1596]
Usings formulas in the solver you can reference to an other formula by index:

1. E + F

2.  [{1} * C]
...

As it is possible to name formulas, it would be an enhancement if you could reference to the formluar by its name:

D:
1. E + F

P
2. [{D} * C]

If you have a lot of calculations, it is easier to compare the formulas with the cache listing.

Kind regards

Udo

**Comment by S-Man42** [comment]
Interesting :) I will think about this.

**Comment by Birdy2404** [comment]
Isn't this fulfilled already in the values area, as you can put in the formulas there also?

**Comment by UJstr** [comment]
That was my first try. Perhaps it is just a lack of my understanding the documentation.

I did not get any value in a sub-formula working in the main formulas. Calling an index of a formula worked fine. But the different brackets and indices make the formulas harder to read. 

Udo 


`{"id":6,"name":"GC1GP7R - ringwälle","formulas":[{"id":1,"formula":"N 50 45.3[A]4 \nE 007 30.9[B]1","name":"Station 1"},{"id":3,"formula":"D = [{C}*C]","name":"D"},{"id":4,"formula":"[ Rodder - Stromberg]","name":"E"},{"id":5,"formula":"N 50 45.[A][C][A]\nE 007 31.[B][D][{3}]"}],"values":[{"id":1,"key":"A","value":"0"},{"id":2,"key":"B","value":"2"},{"id":3,"key":"Eitorf","value":"7"},{"id":4,"key":"Rodder","value":"3"},{"id":5,"key":"Stromberg","value":"2"},{"id":13,"key":"Kalkahütte","value":""},{"id":16,"key":"C","value":" [B * A + B]"}]}`

**Comment by S-Man42** [comment]
{"id":2,"name":"[Import] GC1GP7R - ringwälle","formulas":[{"id":1,"formula":"N 50 45.3[A]4 \nE 007 30.9[B]1","name":"Station 1"},{"id":4,"formula":"[ Rodder - Stromberg]","name":"E"},{"id":5,"formula":"N 50 45.[A][C][A]\nE 007 31.[B][D][{3}]"}],"values":[{"id":1,"key":"A","value":"0"},{"id":2,"key":"B","value":"2"},{"id":3,"key":"Eitorf","value":"7"},{"id":4,"key":"Rodder","value":"3"},{"id":5,"key":"Stromberg","value":"2"},{"id":13,"key":"Kalkahütte","value":""},{"id":16,"key":"C","value":" B * A + B"},{"id":6,"key":"D","value":"C*C"}]}

**Comment by AndyPuma** [comment]
Hallo Udo @UJstr  ich würde es so machen:

`{"id":71,"name":"ringwälle https://coord.info/GC1GP7R","formulas":[{"id":1,"formula":"N50 45.3[A]4 E007 30.9[B]1","name":"St. 1"},{"id":2,"formula":"N50 45.[A][C][A] E007 31.[B][D][E]","name":"St. 2"},{"id":3,"formula":"N50 45.[B][B][E] E007 31.[D][A][F]","name":"St. 3"},{"id":4,"formula":"N50 45.[G][B][C] E007 31.[A][D][H]","name":"St. 4"},{"id":5,"formula":"A= [A]  B= [B]  C= [C]  D= [D]  E= [E]  F= [F]  G= [G]   H=[H]  I=[I]  J= [J]  K= [K]  X= [X]"},{"id":6,"formula":"N50 45.[E][D][I] E007 31.[C][I][G]","name":"St. 5"},{"id":7,"formula":"N50 45.[B][C][B] E007 32.[B][C][I]","name":"St. 6"},{"id":8,"formula":"N50 45.[B][X] E007 32.[B][X]","name":"St. 7 Final"},{"id":9,"formula":"N50 45.[G][I][G] E007 30.[I][F][F]","name":"St. 8"}],"values":[{"id":1,"key":"A","value":"0"},{"id":2,"key":"B","value":"2"},{"id":3,"key":"Eitorf","value":"8"},{"id":4,"key":"Rodder","value":"2"},{"id":5,"key":"Stromberg","value":"3"},{"id":6,"key":"Melchiorweg","value":"3"},{"id":7,"key":"Siegbrücke","value":"4"},{"id":8,"key":"Werfen","value":"1"},{"id":9,"key":"Ringwällen","value":"2"},{"id":10,"key":"C","value":"Eitorf - Rodder - Stromberg"},{"id":11,"key":"D","value":"Melchiorweg + Siegbrücke"},{"id":12,"key":"E","value":"Eitorf - Werfen - Werfen - Ringwällen"},{"id":13,"key":"Herchen","value":"3"},{"id":14,"key":"Mühlenbachtal","value":"6"},{"id":15,"key":"F","value":"Herchen + Mühlenbachtal"},{"id":16,"key":"Alsen","value":"1"},{"id":17,"key":"Kalkahütte","value":"1"},{"id":18,"key":"G","value":"Siegbrücke + Stromberg"},{"id":19,"key":"H","value":"Ringwällen + Alsen + Siegbrücke - Kalkahütte"},{"id":20,"key":"I","value":"3 * Ringwällen - Alsen + Siegbrücke + Melchiorweg"},{"id":21,"key":"J","value":"F - G"},{"id":22,"key":"K","value":"Kalkahütte"},{"id":23,"key":"breite","value":"2"},{"id":24,"key":"höhe","value":"4"},{"id":25,"key":"X","value":"breite * höhe * J * K + A"}]}`

**Comment by UJstr** [comment]
Thx for the additional information. Got it.

In my opinion, it is a bit confusing when the formulas for calculating individual values are in the section of the variables. For my usage, variables should only contain the values that I should enter on the go.

But that's more a general question of design.

**Comment by S-Man42** [comment]
Well, it was a feature request once ;)
