### ISSUE TITLE
Generated prime numbers list is not correct

### ISSUE THREAD

**Issue by musketon-be** [S-Man42/GCWizard#1605]
When I ask to generate prime numbers consisting of 2 numbers, it generates following list:
11, 13, 17, 31, 71, 73, 79, 97
When I take the n-th prime number, and I iterate through e.g. n=0..10, then I see the same sequence appearing.
This list is definitely not a correct list of prime numbers.

I observed above behavior both in the android app version as on the webpage of GCWizard.

In the help page (https://blog.gcwizard.net/manual/en/prime-numbers/01-what-are-prime-numbers/), it is mentioned correct though:
2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, …

**Comment by S-Man42** [comment]
Hi, I can confirm this as a bug, we will have view onto this.

**Comment by S-Man42** [comment]
Hi, could you please tell us, how did you find this tool. It looks like you used the tool for "Permutable Primes" which only shows the primes which give you a prime in every order of their numbers

13, 31
71,17
113, 131,311

If you are not quite sure about which tool it is, click at the ? in the corner, copy the link an have a look at this, which should provide the full tool's name.

Nonetheless we should enhance the look and feel here...

**Comment by musketon-be** [comment]
Hello,

Yes, it seems you are right! I was indeed using the tool for 'Permutable Primes' (in Dutch it is translated as 'Absolute Priemgetallen' which I thought was what I needed (not realizing that Absolute Primes are different from the regular primes).
I wanted to generate all (regular) primes consisting of 2 digits. But apparently this tool does not exist for regular primes, while it does exist for the Permutable Primes. So it was kind of misleading for me. Is it correct that such function does not exist?

Note also that if I search e.g. for 'prime number digits', I get 2 hits, which seem to be exactly the same, but they aren't:
![image](https://github.com/S-Man42/GCWizard/assets/157758562/80f4548f-22d2-453d-8f30-592ced421a14)
One belongs to the Mersenne Prime group and the other belongs to Permutable Primes. From the hits in the search you cannot tell what is what. It would be nice to indicate the parent they belong to.

Thanks for the feedback! Instead of calling this issue a bug, I would rather turn it into:
1) new Feature (add Number Digits function for regular Primes)
2) Enhancement (better indication to which parents the search results belong).
What do you think?

Regards!

**Comment by S-Man42** [comment]
Yes you are right with all that. We will enhance this in the next version. Thanks for pointing that out. You will be added to our testers list. What name would you like to be named?

**Comment by musketon-be** [comment]
Ok, thanks! I will be glad to test it!
You can use 'musketon' as my nickname.

**Comment by t-m-z** [comment]
![image](https://github.com/S-Man42/GCWizard/assets/2946628/31c5748e-edf9-4a3e-b730-834eacfc2977)

**Comment by t-m-z** [comment]
![image](https://github.com/S-Man42/GCWizard/assets/2946628/d29dc145-d8c5-4ad3-9325-af0c1cdd9537)

**Comment by t-m-z** [comment]
![image](https://github.com/S-Man42/GCWizard/assets/2946628/4f08ad0d-274c-4c0f-bb6e-a2d6bdebd48c)
