### ISSUE TITLE
Plejaran Alphabet

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1659]
https://www.futureofmankind.co.uk/Billy_Meier/File:Three_Books_of_Occult_Philosophy_Book_III_p439.jpg
https://www.futureofmankind.co.uk/Billy_Meier/File:Plejaren_Alphabets.jpg
https://en.wikipedia.org/wiki/Celestial_Alphabet

**Comment by Birdy2404** [comment]
Symboltable is prepared and can be implemented
.../Exchange/Symboltabellen/Pleiadian

The Celestic Alphabet is very similar but the source is worse.
