### ISSUE TITLE
Chef: Language switcher does not work

### ISSUE THREAD

**Issue by JanRei** [S-Man42/GCWizard#1660]
Affects: [Chef](https://gcwizard.net/#/chef)

The language switcher at the top of the page does not work for me. When I click on it, the output is regenerated, but the language is not changed. Instead, the tool seems to use the language of the user interface. If I select German in settings, the result is in German. Otherwise, it is in English.

The behavior is the same on the web and the app.

**Comment by S-Man42** [comment]
Check, we can reproduce it, thanks.

We will add you to our testers list for this help :)
