### ISSUE TITLE
Segment Bearings: Bearing to Coordinate shows grey screen 

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1663]
Hi,

I think I found a bug and couldn't find it in the issues (or overlooked it).

- **Tool**: Segment Bearings
- Se**ction**: Bearing 1 and Bearing 2 
- **Issue**: When the Switch Bearing Value <-> Bearing to Coordinates is set to  Bearing to Coordinates a grey box appear

Explanation:

I tested it in Dutch and in English, on Android and on the web. The same thing happens every time.
On the screenshot there are no coodinates, but the same issues appear with coordinates as well.

![IMG_20240506_120043](https://github.com/S-Man42/GCWizard/assets/51774787/c3378fdd-5713-4917-82cb-3c60e4f7d05a)

If you need more information, feel free to ask.

Kind regards Marcia

**Comment by Mike-3** [comment]
We can reproduce it, thanks.

**Comment by S-Man42** [comment]
Fixed.
