### ISSUE TITLE
Geovlog Codes

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1673]
via email:

Hi,

I came across a few codes which I couldn't find in GC Wizard:
https://www.geovlogs.nl/geovlogs-code
https://www.geovlogs.nl/tll-code

It would be Nice if these are adder to the already extensive code database.

Best regards, George (team Geo_reg_Cachong)

**Comment by Linsty** [comment]
I saw the copyrights, so I assume we need permissions first.
I don't know if this is already done, but I can help with that and contact Rogier.

**Comment by S-Man42** [comment]
@Linsty Thanks. Please contact @t-m-z beforehand. He already wrote such emails.

**Comment by Linsty** [comment]
Today I sent the mail and received the permissions.
Sent it to the gc wizard mail with a refer to this issue.

**Comment by Birdy2404** [comment]
.../Exchange/Symboltabellen/TLL is prepared
Geovlogs in work

**Comment by Birdy2404** [comment]
.../Exchange/Symboltabellen/geovlog
Ready for implementation
