### ISSUE TITLE
n-Segment crashed with unknown character + dot or comma

### ISSUE THREAD

**Issue by capoaira** [S-Man42/GCWizard#168]
If I type an unknown character and then a comma or dot, the display crashes and only shows a gray background.
It is likely because dots and commas added to the last character displayed. However, if the character is unknown, there is none.

**Comment by S-Man42** [comment]
Thanks for reporting, nice catch!

fixed in https://github.com/S-Man42/GCWizard/commit/bcefb64a192de2c61264591ae89a5486b6683fa7
