### ISSUE TITLE
GCW Script: IF statement issue

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1686]
When I enter the following script, I don't get any errors and I get the expected output in Android and Webversion.

FOR I = 1 TO 10 STEP 1
A = MOD(I,2)
IF A = 0 THEN
PRINT I,"STRAIGHT"
ELSE
PRINT I,"ODD"
ENDIF
NEXT
![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/b9adaae7-0cb7-4fe1-882b-ee0b59a2c645)

But when I add an ELSEIF to it, the FOR loop stops.
FOR I = 1 TO 10 STEP 1
  A = MOD(I,3)
  IF A = 0 THEN
    PRINT I,"DIVISIBLE BY 3"
  ELSEIF A = 1 THEN
    PRINT I,"REMAINDER 1"
  ELSE
    PRINT I,"REMAINDER 2"
  ENDIF
NEXT
![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/e48f89c0-ba74-480f-8529-377064f6d1d3)

Outside of a Loop the ELSEIF Statement works fine 
A = 1

IF A = 0 THEN
  PRINT "Test 0"
ELSEIF A = 1 THEN
  PRINT "Test 1"
ELSE
  PRINT "Test 2"
ENDIF

PRINT "Expected output: Test 1"

However when I give A the value 0 then the scripts slows down extremely (both android and web version)
When A = 1 or A = 2 then the results appear within 1 second. 
When A = 0 I don't get any results (well, waited for 10 minutes, and then stopped)
![Screenshot_2024-06-02-14-40-53-31_1ff1832a1b21eaa3a9bbb1cecfba658d](https://github.com/S-Man42/GCWizard/assets/51774787/3cb7e0fb-c44a-4947-83ae-54edf20cd7f4)

Should I make another issue from this performance issue?

Kind regards,

Marcia

**Comment by t-m-z** [comment]
Please assign it to me directly 

Sent from MailDroid

-----Original Message-----
From: Marcia ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Subscribed ***@***.***>
Sent: So., 02 Juni 2024 14:47
Subject: [S-Man42/GCWizard] GCW Script: IF statement issue and performance issue (Issue #1686)

When I enter the following script, I don't get any errors and I get the expected output in Android and Webversion.

FOR I = 1 TO 10 STEP 1
A = MOD(I,2)
IF A = 0 THEN
PRINT I,"STRAIGHT"
ELSE
PRINT I,"ODD"
ENDIF
NEXT
![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/b9adaae7-0cb7-4fe1-882b-ee0b59a2c645)

But when I add an ELSEIF to it, the FOR loop stops.
FOR I = 1 TO 10 STEP 1
  A = MOD(I,3)
  IF A = 0 THEN
    PRINT I,"DIVISIBLE BY 3"
  ELSEIF A = 1 THEN
    PRINT I,"REMAINDER 1"
  ELSE
    PRINT I,"REMAINDER 2"
  ENDIF
NEXT
![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/e48f89c0-ba74-480f-8529-377064f6d1d3)

Outside of a Loop the ELSEIF Statement works fine 
A = 1

IF A = 0 THEN
  PRINT "Test 0"
ELSEIF A = 1 THEN
  PRINT "Test 1"
ELSE
  PRINT "Test 2"
ENDIF

PRINT "Expected output: Test 1"

However when I give A the value 0 then the scripts slows down extremely (both android and web version)
When A = 1 or A = 2 then the results appear within 1 second. 
When A = 0 I don't get any results (well, waited for 10 minutes, and then stopped)
![Screenshot_2024-06-02-14-40-53-31_1ff1832a1b21eaa3a9bbb1cecfba658d](https://github.com/S-Man42/GCWizard/assets/51774787/3cb7e0fb-c44a-4947-83ae-54edf20cd7f4)

Should I make another issue from this performance issue?

Kind regards,

Marcia

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/issues/1686

**Comment by Linsty** [comment]
Hi,
I can't assign it to you directly, but mentioned you in  [1687](https://github.com/S-Man42/GCWizard/issues/1687)

**Comment by t-m-z** [comment]
FOR I = 1 TO 10 STEP 1
A = MOD(I,3)
IF A = 0 THEN
PRINT I,"DIVISIBLE BY 3"
ELSEIF A = 1 THEN
PRINT I,"REMAINDER 1"
ELSE
PRINT I,"REMAINDER 2"
ENDIF
NEXT

**Comment by t-m-z** [comment]
is related to issue 1687 - and therefore corrected
