### ISSUE TITLE
Script GCW Script Case - Switch works in Web version but keeps loading in Android

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1688]
Hi @t-m-z 

When executing the example script of the [Swich - Case - default manual page](https://blog.gcwizard.net/manual/en/control-structures/switch-case-default-2/) in the webversion, the script works correct.

![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/d1d9e998-77ad-4a21-bf78-ea93defa24a6)
(Example Web version)

When executing the same script in Android. The script keeps searching and finally getting no results.
![IMG_20240603_082504](https://github.com/S-Man42/GCWizard/assets/51774787/248f4fc3-86fb-42fb-8fc1-912d0128cfce)
(Android version)

Example script

On Screen I added a BREAK command, but without this command the script reacts the same.

Feel free to contact if you need more info

Kind regards,

Marcia

**Comment by t-m-z** [comment]
FOR I = 1 TO 10
  SWITCH I
    CASE 1
      A = "ONE"
      PRINT A
      BREAK
    CASE 2
      A = "TWO"
      PRINT A
      BREAK
    CASE 3
      A = "THREE"
      PRINT A
      BREAK
    DEFAULT
      A = "NEITHER 1 NOR 2 NOR 3"
      PRINT A
  ENDSWITCH
NEXT
