### ISSUE TITLE
CONVERTFROM gives INVALID NUMBER OF PARAMETERS

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1690]
Hi @t-m-z 

When translating and testing the function: CONVERTFROM, I keep getting the same error message:
INVALID NUMBER OF PARAMETERS. I receive this error message in both the web version and on Android.

I used the example script:
DIM C
LISTADD(C, 10)
LISTADD(C, "S")
LISTADD(C, 581050.3657)
LISTADD(C, 4142081.4108)
CONVERTFROM(3)
PRINT GETLAT()
PRINT GETLON()

and I tested it from a command with CONVERTTO and using the same parameter (tested with DMM (1), UTM (3), and SLIPPY MAP (1430)).
This CONVERTTO function works correctly, in my opinion.

![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/e779ac36-7bd0-49cc-b719-d0a539abde4f)

Kind regards,

Marcia

**Comment by Linsty** [comment]
Sorry, I see the mistake. I will mail you to change the manual

**Comment by t-m-z** [comment]
update done
