### ISSUE TITLE
LISTFROM syntax error (GCW Script)

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1692]
Hi @t-m-z 

According to the manual the correct command is: `LISTFROM(string, object)`
(Not sure, but I had the impression the source code 
Every time I give 2 parameters I get the same error: `SYNTAX ERROR: PARANTHESES MISSING`
![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/b735b628-c9c0-4bdd-8791-d5f3ed1dbb70)
If I give just 1 element I get no error, but nothing happens.

I did the following tests: (Line 10 - 40 never changed)

```
10 DIM A
20 LISTADD(A, "test")
30 LISTADD(A, "Hello")
40 PRINT A
```

Variable B is not generated:
```
50 LISTFROM(B,A)
50 LISTFROM("B",A)
50 LISTFROM(B,"A")
50 LISTFROM("B","A")
50 DIM B
60 LISTFROM(B,A)
50 DIM B
60 LISTFROM("B",A)
50 DIM B
60 LISTFROM(B,"A")
50 DIM B
60 LISTFROM("B","A")
(And all variants with A as first element and B as 2nd element)
```
Variable B is generated with value 0
```
50 LISTFROM((B),A)
50 LISTFROM(B(A))
50 LISTFROM(B(A))
50 LISTFROM((B),"A")
```

Tested in both versions (online and android)

Kind regards,

Marcia

**Comment by t-m-z** [comment]
![image](https://github.com/S-Man42/GCWizard/assets/2946628/c3bb6dde-15df-44aa-b228-6bcc2faddb7f)
fixed
