### ISSUE TITLE
Gronsfeld Cipher doesn't appear in navigation Encryption and Codes

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1711]
Hi

According to the manual, the Gronsfeld Cipher should be in the Encryption and Codes menu.
However, when you navigate to this menu, you cannot find this function. I also didn't find the function in other menus.
If you search for "Gronsfeld," you do find the function and it works correctly.
![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/d0d75043-5a71-4da3-b3ae-7eca5e7e8fc1)

Kind regards

Marcia

**Comment by Linsty** [comment]
![Screenshot_2024-06-24-15-38-51-22 1](https://github.com/S-Man42/GCWizard/assets/51774787/2a7e20ef-38ea-4bf1-b2e3-a15c793e3540)

**Comment by Linsty** [comment]
Thanks a lot. I will explain in the manual

**Comment by S-Man42** [comment]
However, maybe it could make sense, to put it separately because nobody knows about the vigenere relation??

**Comment by Linsty** [comment]
To be honest, I don’t think it’s necessary to move the location, because in the description of both ciphers, the vigenere is mentioned.
@t-m-z  It might be a good idea to move both ciphers to the Vigenere folder for consistency?

**Comment by t-m-z** [comment]
Yes Valid point. I agree.

Sent from MailDroid

-----Original Message-----

**Comment by Linsty** [comment]
No issues

**Comment by Linsty** [comment]
I added 2 folders to vigenere cipher (gronsfeld Trithemius) to the dutch manual

**Comment by t-m-z** [comment]
I will adapt DEU and ENG

Sent from MailDroid

-----Original Message-----
