### ISSUE TITLE
Center of 3 coodinats result is wrong

### ISSUE THREAD

**Issue by flowein** [S-Man42/GCWizard#1715]
I enter 3 coordinates: 
N48° 59.147'   E9° 35.856'
N49° 02.881'   E9° 31.174'
N49° 02.018'   E9° 25.939'

and the result was N48° 59.028'   E9° 29.860' which is positioned outside of the triangle
![Center Triangle](https://github.com/S-Man42/GCWizard/assets/160396756/337215cb-88e4-4aa9-9cc6-824b22d357d5)
![Screenshot_App](https://github.com/S-Man42/GCWizard/assets/160396756/6643ccc6-1da2-496a-acfe-fe0b021ec779)

**Comment by AndyPuma** [comment]
Hallo flowein,
Der Untertitel von Mittelpunkt von 3 Koordinaten ist "alle Punkte gleich
weit weg vom Ergebnis" und dies ist erfüllt.
Grüsse Andy

flowein ***@***.***> schrieb am So., 30. Juni 2024, 09:30:

**Comment by flowein** [comment]
Hallo AndyPuma,
deine Antwort ist sachlich richtig. 
Die Frage die sich mir dadurch stellt: Mit welcher Entfernung wird dann berechnet? Denn es gibt ja für jede beliebige Entfernung von den 3 Koordinaten (die größer ist als die zum Mittelpunkt) immer genau 2 Schnittpunkte. Ist das Ergebnis dann ein Zufallswert generiert aus einer zufälligen Entfernung und dem ersten Ergebnis?
Und zumindest das Icon der Funktion suggeriert, dass es sich bei der Ergebniskoordinate um den Mittelpunkt des Dreiecks handelt. Ich interpretiere den Zweck Untertitel so, dass man als user erkennen kann, ob es sich bei der Berechnung um Mittelpunkt oder Schwerpunkt handelt.
Grüße
Flo

> Hallo flowein, Der Untertitel von Mittelpunkt von 3 Koordinaten ist "alle Punkte gleich weit weg vom Ergebnis" und dies ist erfüllt. Grüsse Andy flowein ***@***.***> schrieb am So., 30. Juni 2024, 09:30:
> […](#)

**Comment by Birdy2404** [comment]
Hallo Flo,
In 2D gedacht bildet man einen Kreis aus den 3 Punkten und nimmt dann den Mittelpunkt. Somit kein Zufallswert ;-)
Gruß
Der zweite Andreas :-)

**Comment by S-Man42** [comment]
Hallo Flo,

Die Frage ist letztlich, was erwartest du als Mittelpunkt? Fachlich ist es korrekt, wenn bestimmte Punkte außerhalb eines Dreiecks liegen, insbesondere in einem stumpfen. Diese Funktion gibt den Mittelpunkt des Umkreises aus und damit den EINZIGEN Punkt, von dem alle drei Punkte gleich weit weg sind. Und das hat hat keineswegs etwas mit Zufall zu tun, sondern ist klar definiert. Die Skizze soll nur einen groben Eindruck vermitteln, um was es sich bei der Berechnung handelt. Und es ist klar beschrieben, was es wirklich ausgibt ;) Und nein, dafür gibt es keine zwei Lösungen (außer in Extremfällen auf der anderen Seite der Erde bei dem Körper oder an den Polen, aber das lassen wir mal außer Acht jetzt hier in der Diskussion). Es gibt zwar bei zwei Punkten unendlich viele Schnittpunkte, aber nur bei einem dieser trifft es auch zu, dass auch der dritte Punkt exakt die richtige Entfernung hat...

Die Frage bleibt letztlich, was erwartest du von einem "Mittelpunkt"? Es gibt darauf viele Antworten, weil es viele besondere Punkte gibt: Umkreismittelpunkt (liegt bei stumpfen Dreiecken stets außerhalb), Inkreismittelpunkt, Schwerpunkt (= Centroid, liegt bei stumpfen Dreiecken ebenfalls außerhalb), einfach das arithmetische Mittel der Punkte (selbst der könnte, glaube ich, außerhalb liegen) ? Bis auf den Inkreis stellt der GCW Funktionen bereit.

Gruß Mark
- nicht Andreas -

**Comment by AndyPuma** [comment]
Parallel habe ich es mal mit MOPSOS Skript Funktionen (http://www.mopsos.net/Script.html) nachgestellt und dann mit Freie Karte (GCW) gezeichnet. Währenddessen hat Mark auch schon geantwortet 😲 
Wie Mark schon geschrieben hat, es ist der Umkreismittelpunkt (so heißt auch die MOPSOS Script Fuktion UmKreis(lat1, lon1, lat2, lon2, lat3, lon3, latRes, lonRes, R);)
![Umkreismittelpunkt](https://github.com/S-Man42/GCWizard/assets/62543251/1248caf0-8675-4e9f-a70a-b789c424e91b)

**Comment by flowein** [comment]
Hallo Andreas,
ja das klingt logisch. Mit dem Zufallswert hatte ich mich auf die Aussage von Andreas bezogen, dass von allen 3 Punkten die gleiche Entfernung besteht. Da wäre nämlich so einiges denkbar, aber wahrscheinlich wenig sinnvoll.

Danke für deine Erläuterung, das bringt mir gerade gedankliche Klarheit und ich habe meine alte Formelsammlung raus gekramt. Die Funktion gibt also den Umkreismittelpunkt aus und dieser kann schon mal außerhalb des Dreiecks liegen.
Ich war gedanklich auf der Suche nach dem Innkreismittelpunkt und damit auf dem Holzweg.
Vielen vielen Dank euch, dass ihr euch so viele Mühe mit mir und meinem Brett vor dem Kopf gemacht habt und einen schönen Sonntag.
Grüße
Flo


> Hallo Flo, In 2D gedacht bildet man einen Kreis aus den 3 Punkten und nimmt dann den Mittelpunkt. Somit kein Zufallswert und auch mathematisch richtig bezeichnet ;-) Gruß Der zweite Andreas :-)

**Comment by S-Man42** [comment]
Hi Flo, dass es mehrere Lösungen für den gleichen Abstand gibt, glaube ich nicht. Denn es ist ja klar definiert, dass genau dann wenn alle Punkte den gleichen Abstand zu einem Punkt haben (also alle den Radius eines Kreises zu dessen Mittelpunkt haben), dann hat man den Umkreis. Es gibt keine zwei Umkreise und damit auch keine unterschiedliche Radien, auf denen die Punkte liegen können (bei zweien das was anderes!). Der Umkreis ist fest definiert als genau der eine Kreis, an auf dem alle Punkte liegen, die von einem anderen Punkt - dem Mittelpunkt - gleich weit weg sind.

**Comment by flowein** [comment]
Ja auch da hast du recht. Ich glaub ich bin heute nicht auf der Höhe. Sorry, für den Aufwand und danke, dass ihr mit geduldig und freundlich zugehört habt.
