### ISSUE TITLE
urwigo Hash nur Kleinbuchstaben 

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#1739]
https://gcwizard.net/#/urwigo_hashbreaker

Der Urwigohash wird standardmäßig immer aus  _Urwigo.Hash(string.lower(input)) =
gebildet

**Comment by S-Man42** [comment]
Yes, and what exactly is wrong with it?

**Comment by AndyPuma** [comment]
Thomas weiß bescheid. Er wollte nur den Eintrag als reminder.
Aktuell wird Groß-/Kleinschreibung unterschieden, was dazu führt, wenn man
im WIG z.B. Test eingibt, ergibt das den Wert von test = 46376 im GCW wird
aber Test = 7288 berechnet

Vorschlag immer in lower konvertieren und evtl. Knopf Abschaltung von
lower??

MLorenz42 ***@***.***> schrieb am Do., 4. Juli 2024, 07:23:

**Comment by S-Man42** [comment]
Nein, wenn es falsch ist, ist es falsch. Dann sollte es richtig berechnet werden :)
