### ISSUE TITLE
Center point of 3 coordinates freezes again

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1741]
In der vorherigen Version hat Centerpoint of 3 coordinates noch normal funktioniert. 
Jetzt scheint sie jedoch wieder einzufrieren. (Nach 15 Minuten noch immer kein Ergebnis)

(Webversion + Android)

![Screenshot_2024-07-04-21-42-00-98_1ff1832a1b21eaa3a9bbb1cecfba658d 1](https://github.com/S-Man42/GCWizard/assets/51774787/a289c9d3-d700-4fa5-a6a9-c379fa35614c)
Viele Grüße,
Maria

**Comment by AndyPuma** [comment]
Leider kann man auf dem Screenshot nicht alle Werte lesen. Ich kann mir
vorstellen das es Konstellationen gibt wo kein Umkreis gebildet werden kann.

Marcia ***@***.***> schrieb am Do., 4. Juli 2024, 21:47:

**Comment by AndyPuma** [comment]
Mit der NB 3.1.1 (Build: 271) geht es

Marcia ***@***.***> schrieb am Do., 4. Juli 2024, 21:47:

**Comment by S-Man42** [comment]
No chamge in any of the versions (currently working on it). However... Unfortunately it happens rare case that no found is delivered... Did you try again? When you say in previous it worked: Did you try with exactly the same coords?

**Comment by Linsty** [comment]
8 pm My mom discovered it didn't work with these coords. (Android)
When I reproduced it, I had the same issues with the same coords in both versions (Android + Web)

10 pm: Andy tested in NB no problems.

11.30 pm:
no issues too. 

Do we know what causes this?

**Comment by S-Man42** [comment]
yes... and no... i know what exactly is zhr reason for freezing. But I did not discover under whivh conditions it is doing this stuff. It seems to be random. However. I am currently implementing a new one nonetheless, so I will not doing any investigation on this.
