### ISSUE TITLE
Alphabet values: Removing alphabet button removes all custom alphabets (Android)

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1743]
Function: Alphabet Value
Bug: Remove Alphabet
Version: Android 

When you want to remove 1 custom alphabet, GCW removes all custom alphabets:

Screenshot1: Menu before removing custom alphabet:
![Screenshot_2024-07-06-18-15-31-15_1ff1832a1b21eaa3a9bbb1cecfba658d 1](https://github.com/S-Man42/GCWizard/assets/51774787/1174a066-24b4-40d5-bc52-95da56af333e)

Screenshot 2: Remove Alphabet ABC
![Screenshot_2024-07-06-18-09-03-94_1ff1832a1b21eaa3a9bbb1cecfba658d 1](https://github.com/S-Man42/GCWizard/assets/51774787/a0de3e8f-e2ca-405c-abac-fb84e018ced9)

Screenshot3: Menu after removing custom alphabet:
![Screenshot_2024-07-06-18-16-27-21_1ff1832a1b21eaa3a9bbb1cecfba658d 1](https://github.com/S-Man42/GCWizard/assets/51774787/aa338c62-fd5b-409c-bcc4-56a90f25eccf)

Expected output: 
![afbeelding](https://github.com/S-Man42/GCWizard/assets/51774787/0437ac6b-934f-4b1a-a3bc-7fac7c956ba5)

In Webversion it works as expected.

Kind regards,

Marcia

**Comment by S-Man42** [comment]
Wow...from my point of view it makes no sense that web and android behave differently. Could you please double check this?

**Comment by Linsty** [comment]
Yes...checked it several times 
Even checked webversion on Windows laptop and Android Chrome mobile.
Both work correct but not in GCW Android app

**Comment by S-Man42** [comment]
hmmm. ol

**Comment by AndyPuma** [comment]
Marcia, kannst du bitte die Versionsnummer von allem nennen (bei mir zeigt
der Browser 3.1.1 (Build: 270)  App auch. Haben aber schon oft gehabt das
der Browser erst nach mehrfach F5 Refresh erst die neue Version  übernommen
hat.

Marcia ***@***.***> schrieb am Sa., 6. Juli 2024, 20:33:

**Comment by Linsty** [comment]
Allen: Browser 3.1.1 (Build: 270)

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Linsty** [comment]
Ich habe es gerade auch auf einer App auf einem anderen Android phone getestet. Genau das gleiche Problem.
