### ISSUE TITLE
RSA Encryption: Inconsistent handling of non-prime numbers

### ISSUE THREAD

**Issue by JanRei** [S-Man42/GCWizard#1758]
Affects: [Various RSA Encryption tools](https://gcwizard.net/#/rsa_selection)
Version: 3.1.1 (270), web and iOS (version 17.5.1 on iPhone 12)

The following tools just show an empty output if I provide non-prime numbers for p and q:
- RSA public key e Checker
- RSA public key d Checker

The following tools also show an empty notification (white box) in this case:
- RSA Encryption
- RSA private key d Calculator
- RSA N Calculator
- RSA φ Calculator

In my opinion, this is inconsistent and it would be more helpful if there would be an error message so I know why no result can be given. I have found suitable texts in the translation files which could be used:
```json
"rsa_error_p.not.prime": "p is not a prime number",
"rsa_error_q.not.prime": "q is not a prime number",
```

**Comment by Mike-3** [comment]
Thanks for the hint.
