### ISSUE TITLE
Suggestion for symbol table: fringe glyphs

### ISSUE THREAD

**Issue by Linsty** [S-Man42/GCWizard#1760]
https://fringe.fandom.com/wiki/Glyphs
https://fringeconnections.com/glyphs

**Comment by S-Man42** [comment]
hm... how about the copyright? Not even from this website but also from the tv series itself?

**Comment by Linsty** [comment]
What I've found so far:
https://web.archive.org/web/20110405162851/http://fringepedia.net/wiki/Template_talk:Site_Disclaimer
https://www.fox.com/article/fox-networks-sites-and-services-terms-of-use-agreement-597bc239ef528f0026dc0316/

**Comment by S-Man42** [comment]
Well I don't believe so. And I don't want to get in any conflict with Fox/Disney:

FOX only grants non-exclusive, royalty-free license to users to **download** and use a **single** copy of the media for the term of the agreement and **strictly for promotional purposes**

Nothing about re-publishing under a free license. Only for private usage.

**Comment by Linsty** [comment]
Ok, I understand

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
