### ISSUE TITLE
Extreme performance problems at IATA Search

### ISSUE THREAD

**Issue by olliklee** [S-Man42/GCWizard#1782]
If there is only one letter in the search for airport name. for example 'a'. The search takes for ever and the app becomes unresponsive.
The problem could be solved when the search only starts with at least 2 characters. 

![IMG_3637](https://github.com/user-attachments/assets/331bbc2a-289e-4cf3-801b-c1ff74d4a91b)

The heap gets exhausted.

**Comment by S-Man42** [comment]
Did you only try this in the emulator? The emulator is always! slow as hell.

On my phone it take about 1 second. For me no reason to change something.

**Comment by olliklee** [comment]
Web, iPhone, Android Emulator.

**Comment by S-Man42** [comment]
of course

**Comment by S-Man42** [comment]
nonetheless it seems not a bad idea. please ask @t-m-z if he has any concerns

If you fix it, please create a error message or something. (just output a teyt instead of the table)

**Comment by t-m-z** [comment]
No concerns

**Comment by olliklee** [comment]
Makes a more universal solution in the multiline_column output widget not the better way? I'm thinking about putting the rows into a lazy list, which loads while scrolling. I found that, but I don't dare to put my hands on a commonly used widget in the project:  https://medium.com/@chetan.akarte/what-is-lazy-loading-in-flutter-explain-with-example-4614e7d9e4d0 
What do the widget experts think?

**Comment by t-m-z** [comment]
Sounds reasonable.
However for the first step we should avoid searching only for on letter

Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
> Makes a more universal solution in the multiline_column output widget not the better way? I'm thinking about putting the rows into a lazy list, which loads while scrolling. I found that, but I don't dare to put my hands on a commonly used widget in the project: https://medium.com/@chetan.akarte/what-is-lazy-loading-in-flutter-explain-with-example-4614e7d9e4d0 What do the widget experts think? To limit the seachtext length seems to be just a workaround, which doesn't hit the problem

Could be done for the ListViews like tool lists or SearchSymbolsByText. But the MultiColumnDingensWidget is not a ListView... However one should think about this. Maybe a task for @Mike-3?

**Comment by Mike-3** [comment]
You can assign it to me. I had already thought about processing the query asynchronously.
