### ISSUE TITLE
Licenses into ToolLicenses

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#1786]
https://github.com/S-Man42/GCWizard/blob/df7935689102a17472ca889a71ef3bf25adef7eb/lib/application/registry.dart#L1474

Einfach alle Tools durchgehen, wo am Code oder im Handbuch ne Quelle angebenen ist und in die Registry eine oder mehrere ToolLicense Objekte erstellen

(Achtung: In der alten license.dart sind teilweise Sachen gruppiert, wie zB nur "astronomy functions" statt genau die Tools wo das genau gebraucht wird)

GCWSymbleTableTool inheriteds from GCWTool, so it is the same.

**Comment by S-Man42** [comment]
Rules:

Code: 
We fork the related Github repository and link to the license point for the explicit most actual commit. So if the license changes or repo will be removed we will not loose the license. And we can be ensure to not generate dead links

If there is no Github repo, generate a link from the wayback machine/internet archive to ensure not going to be lost of sources (like offline astronomie.info). If possible trigger the wayback machine to generate a link from the website

Researches
Wikipedia: Not only link to article but also to the explicit version (via version history of the article)
Books/Articles: Cite them with ISBN, Author, Title, maybe pages, etc.

**Comment by Mike-3** [comment]
Und wie wollen wir das bei den Koordinatensystemen mache ? Das sind ja keine extra Features.

**Comment by S-Man42** [comment]
Ich bin fast vollständig durch da. Alles unter FormatConverter

**Comment by t-m-z** [comment]
okay - habe bei internet Archive einen Account angelegt - und werde damit jeweils einen Snapshot der Web-Seite speichern. Dauert ca. 5min pro Link

**Comment by S-Man42** [comment]
also bei mir geht das auch ohne account.

Ich mache das aktuell so:
1. Wenn Github, dann forken, und davon letzter commit -> browse files -> license. Gibt dann einen link wie etwa github.com/S-Man42/<forkedRepo>/<commitId>/LICENSE
2. Wenn Wikipedia: Artikel aufrufen, Versionshistorie, link auf aktuelle Version
3. Wenn Irgendeine andere Webseite: Link des relevanten Artikels kopieren, Internet Archive öffnen, Link eingeben, letzten bekannten Snapshot auswählen ODER "Snapshot erstellen" klicken, falls noch nicht vorhanden.
4. Wenn Email... Da überlege ich noch. Aktuell nur "Use permission by e-mail (yyyy-mm-dd)". Ich denke drüber nach, die relevante e-mail ins projekt zu kopieren, aber das könnte auch datenschutzrechtlich bedenklich sein.
