### ISSUE TITLE
Intelligent Clipboard

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#18]
Copying and pasting data to inputs can be frustrating, especially at the coordinates section.

- internal enhanced clipboard with 10 slots or so.
- enriched with metadata, to know WHAT has been copied. So, maybe you copy a DD°MM.MMM coordinate, but want to paste it into a new coordinate field DD.DDDD. Then it would be great to know, that your clipboard data is a coordinate and how to convert it to fit into your new widget.
- for pasting external data (e.g. coordinates from c:geo) a simple parser which guesses, what kind of data it could be.
- adding a copy button to every output text

**Comment by AndyPuma** [comment]
> 
> 
> Copying and pasting data to inputs can be frustrating, especially at the coordinates section.
> 
>     * internal enhanced clipboard with 10 slots or so.

coole Idee 

>     * enriched with metadata, to know WHAT has been copied. So, maybe you copy a DD°MM.MMM coordinate, but want to paste it into a new coordinate field DD.DDDD. Then it would be great to know, that your clipboard data is a coordinate and how to convert it to fit into your new widget.

kling ganz schön kompliziert 
 
>     * for pasting external data (e.g. coordinates from c:geo) a simple parser which guesses, what kind of data it could be.
> 
ich glaube in LOCUS erkennt die App auch anhand der Schreibweise Koordinaten und konvertiert sie auf das gerade eingestellt Format
>     * adding a copy button to every output text

**Comment by S-Man42** [comment]
Paste List

https://github.com/S-Man42/GCWizard/commit/0dc028d1948a755223021f19ab404dfbdc1c6583

**Comment by S-Man42** [comment]
Together with #112 and #744 and the ability to paste any coordinate format, the clipboard is extremely developed. I am not quite sure if more effort yields much better workflows/experience.
