### ISSUE TITLE
colorize solmisation - solresol - according to geocaching toolbox

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1807]
https://www.geocachingtoolbox.com/index.php?lang=en&page=codeTables&id=solresol

**Comment by S-Man42** [comment]
Why? Is there a more common specification for that or is it an invention from GTB? What if dCode would color it other way round? It is not quite clear to me, why I should do this :)

**Comment by t-m-z** [comment]
https://de.wikipedia.org/wiki/Solresol

;-)


Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
Check
