### ISSUE TITLE
grey screen WIG Analyzer @ 3.2.0 (Build: 276) @ Android

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#1830]
@t-m-z  wie per Threema beschrieben kommt es bei folgenden WIG https://www.wherigo.com/cartridge/details.aspx?CGUID=45182190-aad7-478d-8374-af8ed10a6343 zu grey screens bei "Liste de Eingabeobjekte mit möglichen Antworten"  beim umschalten der "Möglichen Antwort 1/2" von 1 auf 2 bzw. bei den weiteren Antworten auch

**Comment by t-m-z** [comment]
Bestätigt.

Fehler tritt nicht auf bei 3.1.1


Sent from MailDroid

-----Original Message-----
From: AndyPuma ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Thomas ***@***.***>, Mention ***@***.***>
Sent: Di., 06 Aug. 2024 20:25
Subject: [S-Man42/GCWizard] grey screen WIG Analyzer @ 3.2.0 (Build: 276) @ Android (Issue #1830)

@t-m-z  wie per Threema beschrieben kommt es bei folgenden WIG https://www.wherigo.com/cartridge/details.aspx?CGUID=45182190-aad7-478d-8374-af8ed10a6343 zu grey screens bei "Liste de Eingabeobjekte mit möglichen Antworten"  beim umschalten der "Möglichen Antwort 1/2" von 1 auf 2 bzw. bei den weiteren Antworten auch  

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/issues/1830
