### ISSUE TITLE
Kenny Code: Ignore Case Sensitivity

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#187]
(from Pamakaru via WhatsApp)

Sample:
"Mfmfmffmp mfmmppppmmmmmmfmfpfmp!"

--> Current Result: MUIMP GEMACHT!
--> Expected Result: GUT GEMACHT!

Add an OnOffSwitch for "Case Sensitivity" (like in Substitution)

**Comment by Mike-3** [comment]
![Kenny](https://user-images.githubusercontent.com/70719484/93904730-6f723280-fcfa-11ea-99a1-17a4779b34a0.png)
changed
