### ISSUE TITLE
Simmer Index description is a bit wrong

### ISSUE THREAD

**Issue by igorsantos07** [S-Man42/GCWizard#1873]
I stumbled upon [this blog(?) post](https://blog.gcwizard.net/manual/en/summer-simmer-index-perceived-temperature/01-what-is-the-summer-simmer-index/) explaining the Simmer Index is related to "heat at night"... But that's not mentioned anywhere else, not even in the [actual paper](http://summersimmer.com/home.htm). Here's another [scientific source which does not mention night perceptions](https://www.sciencedirect.com/science/article/abs/pii/S2212095522000967#:~:text=Summer%20Simmer%20Index%20which%20is,et%20al.%2C%202010).

Given this index seems to be confined mostly to scientific discussion nowadays, given [it got copyrighted](https://athena.trixology.com/index.php?topic=941.0) and didn't get much adoption beyond the usual Heat Index and Humidex... I would suggest editing that blog post as it became one of the few sources from a quick Google search with simpler explanations about that index.

**Comment by t-m-z** [comment]
Hi Igor,

Thanks for your annotation. I will have a deeper look at it.
However, according to this website https://myscope.net/hitzeindex-gefuehle-temperatur/ the Summer Simmer Index refers to the apparent temperature at night: "Der Summer-Simmer-Index bezieht sich im Vergleich zum Hitzeindex auf die gefühlte Hitze in der Nacht und stellt einen Fraktor für das Unwohlsein dar.

Kind regards 
Thomas 

Sent from MailDroid

-----Original Message-----
From: Igor Santos ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Subscribed ***@***.***>
Sent: So., 08 Sept. 2024 23:28
Subject: [S-Man42/GCWizard] Simmer Index description is a bit wrong (Issue #1873)

I stumbled upon [this blog(?) post](https://blog.gcwizard.net/manual/en/summer-simmer-index-perceived-temperature/01-what-is-the-summer-simmer-index/) explaining the Simmer Index is related to "heat at night"... But that's not mentioned anywhere else, not even in the [actual paper](http://summersimmer.com/home.htm). Here's another [scientific source which does not mention night perceptions](https://www.sciencedirect.com/science/article/abs/pii/S2212095522000967#:~:text=Summer%20Simmer%20Index%20which%20is,et%20al.%2C%202010).

Given this index seems to be confined mostly to scientific discussion nowadays (given [it got copyrighted](https://athena.trixology.com/index.php?topic=941.0) and didn't get much adoption beyond the usual Heat Index and Humidex, I would suggest editing that blog post as it became one of the few sources from a quick Google search with simpler explanations about that index.

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/issues/1873

**Comment by t-m-z** [comment]
It seems, that there are different Summer Simmer Indices. However thanks for your hint I have changed the articles.
