### ISSUE TITLE
Waypoint Projection: Add Compass Rose

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#188]
(From TeamBirdy2404 via email)

Add option to enter N, S, NW, ... as direction inputs.

Maybe add a switch (Input Mode: Compass/Textfield) which switches between the compass rose DropDown and the current TextField input...

But this additional option would make the bearing input look too difficult for non-technophile users...

**Comment by S-Man42** [comment]
[Kompassrose.xlsx](https://github.com/S-Man42/GCWizard/files/5254430/Kompassrose.xlsx)

**Comment by Birdy2404** [comment]
![Peilung](https://user-images.githubusercontent.com/34218281/93806816-08954080-fc4a-11ea-87f4-226b532a4387.jpg)
Would the attached option work?
Backwards could be in a new line and the dropdown next to the inputfield.
If I choose a direction like Northeast, then the correct degree would be set into the inputfield.

**Comment by S-Man42** [comment]
Exactly this has been already prototyped a few hours ago :) Great that you prefer this way too :)

**Comment by S-Man42** [comment]
![compass](https://user-images.githubusercontent.com/16626063/93873119-73d62580-fcd1-11ea-9a6f-2dbc4537dee5.gif)
