### ISSUE TITLE
LSB Steganographie

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1886]
![image](https://github.com/user-attachments/assets/1dd50e26-5995-4f54-a24a-a569ff429da6)

**Comment by Linsty** [comment]
I saw this bug too.
One addition: In webversion the error is different:
![afbeelding](https://github.com/user-attachments/assets/65ca78d4-07f7-450e-ab28-c78a41fddc72)

**Comment by S-Man42** [comment]
@Mike-3 Do you mind you could have a look at this.. It looks like an async problem for which you are more qualified than anybody else...
