### ISSUE TITLE
Visual Cryptography

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#1921]
Key image seems to have no function

**Comment by Mike-3** [comment]
On my test, I have different results with key image and without key image on encode.
Do you have a exemple, what you mean.

**Comment by t-m-z** [comment]
without a key image I get two black & white pictures which have to be combined.
with a key image I get only one black & white image.

I have no clue how to use this key image

**Comment by S-Man42** [comment]
The idea was as follows:

You have one normal visual cryptography pair. Both were created randomly.

Now. you want to create a second pair, but want to use one image of the first pair (lets call it key). You can now load the key image to encrypt the secons picture.

With that you are able to create one "key" image - for example you could give it at the start of a multi - and encrypt different images with that. So you might take the key to different stages and decrypt different hints with the same key image.

Therefore:
1. Create a pair normally for stage 1
2. Switch to create with key: Take one of the previously creates images and the image to be emcrypted -> voila, you get a third VC image for stage two.

**Comment by S-Man42** [comment]
Is here still a problem?

**Comment by Mike-3** [comment]
on progress
