### ISSUE TITLE
Cross sum in the area

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#196]
Crash,Crash / no response if the search area is too large. Search is already running while you are still entering the search area. For example, it is almost impossible to search in the range 999900 to 999950. if the search area is too large.
Optional. Possibly. expand search also iQS.

**Comment by S-Man42** [comment]
I guess, it deals with some kind of integer problems...

**Comment by S-Man42** [comment]
Didn't make the calculation on-the-fly anymore. Added a Submit Button
