### ISSUE TITLE
Waldmeister Converter unterschiedliche Ergebnisse evtl. Abhängig von Einstellung Nachkomma DMM

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#1960]
@S-Man42 

evtl. hat die Einstellung der Nachkommastellen von DMM Einfluss auf die Berechnung, denn nach verstellen der NAchkommastellen auf eine größere Zahl (8) uns wieder zurück auf 3 kam das gleiche Ergebnis raus
Oder es lag evtl. auch daran, dass die Koordinaten über GPS Einlesen in meiner NB angelegt wurden??
Threema Chat Mark - Andy 16/17.10.24
![threema-20241016-221108561](https://github.com/user-attachments/assets/aa027b96-3da4-4798-ab52-8d4c6e2642ad)

**Comment by S-Man42** [comment]
Sehe ich auch so. Waldmeister war noch nie eindeutig. Habe auch keinen Hinweis auf einen Fehler im Code gefunden
