### ISSUE TITLE
Measure own coordinate

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#197]
Get own coordinate: Retrieve several single measurements from the device - average the values... I believe, it's a little harder, because single measurements differ in accuracy, found satellites and so on... 

Maybe this could be a basis for a port to dart?

https://github.com/davidvavra/GPS-Averaging/tree/master/app/src/main/java/org/destil/gpsaveraging/measure

**Comment by t-m-z** [comment]
I believe this will be a basis for a port.

- LocationAverager.java starts the retrieval of gps-data, adds the data to a list, calculates the avarage and stops the retrieval.

- Measurements.java provides the necessary methods and properties
