### ISSUE TITLE
Formelrechner {1} Verweise enthalten { } o. ( )

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#1973]
3.2.1 (Build: 292)

Ergebnis des Aufrufs der Vorformel hat ( ) oder { } drum
Was bisher nicht so war.
![SmartSelect_20241027_113011_1](https://github.com/user-attachments/assets/1b8a6846-111f-4215-814d-cfff2b91018b)
![Screenshot_20241027_112028](https://github.com/user-attachments/assets/4e5eafd3-8e9d-4a79-9ef6-f26368f49d6c)

**Comment by S-Man42** [comment]
Please add your export next time for better debugging.

{"id":17,"name":"https://coord.info/GC929TD","formulas":[{"id":1,"formula":"N[A][B]° [C-A][C-A].[C-A+B][C-B-A][C-B]\nE[C]° [A-B][B].[C-B][C-B][C-B-A]","name":"Erste"},{"id":2,"formula":"{Erste}"}],"values":[{"id":1,"key":"A","value":"5"},{"id":2,"key":"B","value":"3"},{"id":3,"key":"C","value":"9"}]}

**Comment by AndyPuma** [comment]
is the export not visible in the Screenshots?

MLorenz42 ***@***.***> schrieb am Mo., 28. Okt. 2024, 10:05:

**Comment by S-Man42** [comment]
Yes, but a screenshot is not very helpful for debugging. It make the work only harder since I have to rewrite the information. Moreover: Maybe the problem could be not visible like I and l problem or a special whitespace character. An Export makes more sense at all for everything.
