### ISSUE TITLE
Malbolge (Esoteric Programming Language)

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#219]
(My very favorite one... I believe, GCW must include this :D)

- Text To Malbolge (Generator)
- Code Interpreter (Execute Malbolge; Malbolge To Text)

Wikipedia:
https://en.wikipedia.org/wiki/Malbolge

Reference implementations:
Java: 
https://github.com/b441berith/MalbolgeInterpreter
https://bitbucket.org/msagi/malbolge-interpreter/src/334550921a223563e0f2224642787a7b3410c038/?at=feature%2Fmalbolge-interpreter

Rust:
https://github.com/return/malbolge

JavaScript:
https://zb3.me/malbolge-tools/
https://lutter.cc/malbolge/debugger.html

Python:
https://github.com/wallstop/MalbolgeGenerator
http://malbolge.doleczek.pl/

**Comment by t-m-z** [comment]
klingt interessant - aber witziger fände ich SPL: Shakespeare Programming Language 
https://de.wikipedia.org/wiki/Shakespeare_Programming_Language
http://shakespearelang.com/
Das gäbe faszinierende Listings

**Comment by S-Man42** [comment]
Well, when we talk about "funny" codes: There are lots of different languages. My personal favorite is "chef": A programming language whose codes could read as a cooking recipe. You can have a lot of fun with every single esoteric programming language: https://en.wikipedia.org/wiki/Esoteric_programming_language :D

However, Malbolge is a really crazy "encryption" and could be taken for a cipher riddle of highest level. Moreover, with that, some personal things come with that for me. I would love to see it in the GCW. So, if you like: Feel free to implement it!

**Comment by t-m-z** [comment]
Regarding Chef - some hints and links for possible future action:

language description by David Morgan: https://www.dangermouse.net/esoteric/chef.html
Interpreter written in Java: https://github.com/joostrijneveld/Chef-Interpreter

**Comment by t-m-z** [comment]
As far as I read in the meantime, writing an interpreter is not the challenge - its the malbold-code-generating-part

**Comment by t-m-z** [comment]
Some findings:
- There is a contradiction between the original specification and the original interpreter regarding the opcodes for input and output.
- To write an Interpreter - all implementations are helpful/valid and similar
- There are only two kind of generators to be found in the internet with implementations:
  - JavaScript: https://zb3.me/malbolge-tools/ and https://lutter.cc/malbolge/debugger.html
  - Python:  http://malbolge.doleczek.pl/
- the above imlementations are not interoperable!
  - zb3 generates code which can be read by every implemenation
  - doleczek/Python generates code which can only be run by doleczek and self-written interpreter 
     - zb3 provides a "Runtime Error: Illegal Jump" although there is no jump
     - lutter.cc provides a message "Illegal char/opCode" although there is no illegal char 
 I opened an issue at https://github.com/wallstop/MalbolgeGenerator to get further information. wallstop recommended reaching out to the owners of those malbolge interpreters, he believe the generated code is a valid program.  
 Hence I opened an issue at zb3 to get further information.

**Comment by S-Man42** [comment]
Done in #322
