### ISSUE TITLE
Polybios: Replace Encrypt/Decrypt Buttons

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#22]
[from Klumpenkukuk]

The main idea here was:
- The encrypt/decrypt switch can be used for functions that can calculate a result from any input. A separate submit button is not necessary, because every input results in a calculation. But Polybios cannot calculate anything meaningful without a complete key or alphabet.
- So the user has to confirm his/her inputs with a specific click. If this would be a single button (like at the coords calculations) a separate switch would be needed. This would be an extra layout line and an extra click action for the user. So I decided for the buttons

BUT: It is the only (?) function with this behaviour so far and so has its own different layout. Maybe one should think about an alternative. Maybe giving out an empty string when no valid input is there as in other functions?

**Comment by t-m-z** [comment]
I believe, this cannot be decided in general. It is a case by case decision.
There are some more functions which needs specific parameters. E.g. Enigma, Bifid., ADFG(v)X etc.
So we have to consider two cases for encoding/decoding:

1. Encoding/Decoding of a datastream on the fly e.g.Morse
1. Encoding/Decoding of a datablock e.g. Polybios

Hence, according to the type of encoding/decoding, there should be the possibility to use buttons to start the encoding/decoding blockwise or a switch to do the encoding/decoding on the fly.
