### ISSUE TITLE
Implement missing Mopsos features

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#229]
At the very beginning of GCC it was my goal to make the Windows (Portable Windows) tool Mopsos available for Android. Most features made it into the tool.

However, some features are still missing:
[list here]

It would be great to achieve this goal now with the GCWizard

**Comment by Mike-3** [comment]
Where is the missing list ?

**Comment by S-Man42** [comment]
we have tickets for the last few tools
