### ISSUE TITLE
Feature Request: Variable digits in waypoint 

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#23]
Da [GeoMT ](http://geomt.fdev.nl/) leider nicht mehr im Playstore gepflegt wird und aktuell die Variablen Koordinaten auch nicht mehr funktionieren - wäre es schön wenn ihr diese Funktion auch einbauen könntet. :-)
Variable digits in waypoint N 51° 11.4[358]7 E 10° 22.17[456] shows 9 markers 
oder wie auf [Dennis seinem Tool](https://www.multisolver.xyz/mapTools/index.html)  "</>Add Complex"

**Comment by dennistreysa** [comment]
Also quasi sowas? https://www.geocachingtoolbox.com/index.php?lang=en&page=incompleteCoordinates

**Comment by AndyPuma** [comment]
> 
> 
> Also quasi sowas? https://www.geocachingtoolbox.com/index.php?lang=en&page=incompleteCoordinates

Oder auch so Dennis :o) Wobei die direkte Eingabe in [ ] sicher einfacher und schneller wäre

**Comment by S-Man42** [comment]
Duplicate for #11
