### ISSUE TITLE
Coordinates Intersections of Three Circles Crash

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#263]
Crashed with 2 circles with the same center and diameter.

**Comment by Mike-3** [comment]
The same with Intersections of Two Circles

**Comment by S-Man42** [comment]
I cannot reproduce this. Can you explain the exact workflow. What exactly crashed?

**Comment by Mike-3** [comment]
At that moment it worked the first time. The result was no cut points. After that, I've had it twice in a row.
The app is then frozen.
![20201123_151940](https://user-images.githubusercontent.com/70719484/99973946-9a334280-2da0-11eb-90da-dfbcaf6999e2.jpg)
![20201123_152009](https://user-images.githubusercontent.com/70719484/99973962-9c959c80-2da0-11eb-8d45-f6ecd4e7efc1.jpg)

**Comment by S-Man42** [comment]
Ah, same circles... This can be. I have to check this.

**Comment by S-Man42** [comment]
Done #275
