### ISSUE TITLE
Piano key frequences

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#271]
https://de.wikipedia.org/wiki/Frequenzen_der_gleichstufigen_Stimmung

**Comment by Birdy2404** [comment]
[piano_keys.txt](https://github.com/S-Man42/GCWizard/files/6948711/piano_keys.txt)

**Comment by t-m-z** [comment]
please check with french wikipedia, too:
https://fr.wikipedia.org/wiki/Fr%C3%A9quences_des_touches_du_piano

**Comment by Birdy2404** [comment]
[piano_keys.txt](https://github.com/S-Man42/GCWizard/files/6950682/piano_keys.txt)
Added also the 2 french versions
