### ISSUE TITLE
Selection List "Documentation" for the main page

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#286]
Up to now we have only a download button for the symbol tables PDF. 
Another PDF is under construction: the handbook.
A third doc could be "eine Anleitung um Geocaching Mysteries lösen zu lernen, aus Ninas Schmierblo(g)ck, Autor: Nina Geiger, 
Copyright: © 2017 Nina Geiger" from http://www.justchaos.de/blog/ninas_schmierblogck_mysteries_loesen_als.pdf. Maybe she grants the rights to use the pdf and rewrite it into ASCIIDoc with references to the GCWizard?

**Comment by Birdy2404** [comment]
Are there any contact data of Nina Geiger available?

**Comment by Birdy2404** [comment]
@t-m-z Did you get a usefull response from the mailrobot?

**Comment by t-m-z** [comment]
Unfortunately not.

Sent from MailDroid

-----Original Message-----

**Comment by Birdy2404** [comment]
Made a request on Facebook
https://www.facebook.com/groups/258731947489712/permalink/4195400833822784

**Comment by Birdy2404** [comment]
For my kind of view, same opinion

**Comment by t-m-z** [comment]
basicalle - I believe we could close this issue. On the other hand, to get more users maybe we should think about linking to other forums.
However - close it in the meantime
