### ISSUE TITLE
Enhance GCWTool

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#292]
Currently there are two ways to implement a button in the titletrailing:
- using the _onlinehelp-key in the Registry
- using the titleTraining-key in the Registry

The GCWTool checks which key is used and then provide an icon.

How about modifying the GCWTool-Widget adding 
"final List<Widget> action" 
"final List<String> urls"
"final List<String> dialogTitle"
"final List<String> dialogText"
"final List<Icon> icons
This would make the Widget more flexible.
Relevant Icons could be
- Icons.help
- Icons.download
- Icons.article

**Comment by S-Man42** [comment]
Doing this using lists is not a good idea. If you want to do that a list of maps should be better:

```
[
  {
    "title" : "...",
    "icon" : "...",
    "action" : myfunction,
    "..." : "..."
  },
  {
    "title" : "...",
    "icon" : "...",
    "action" : myfunction,
    "..." : "..."
  },
]
```

Or even better: Create a GCWToolAction class and a List<GCWToolAction>

**Comment by t-m-z** [comment]
okay - I assume I am allowed to enhance/provide the (new) widget? Otherwise I would not invest  ;-)

**Comment by S-Man42** [comment]
Why not? It's should nit be very difficult

**Comment by S-Man42** [comment]
#368
