### ISSUE TITLE
Maya Numbers tool

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#315]
Well, @t-m-z demonstrated how we could do things like that in #249. I guess, Maya Code could be done this way as well

**Comment by t-m-z** [comment]
Well - whats about Others Symbols Like Braille, Chappe, Murray, Dancing Men, Semaphore, Genre ich, ...

;-)

Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
I guess they are all not quite necessary because there are no such "adding" function in that. You have 10 symbols for 10 braille numbers. If you need to show the number 123, you will add the braille symbols for 1, 2 and 3. And that can be done using the symbol tables.

The difference to cistercian or maya is, that you are creating different numbers with just ONE symbol. The tool should avoid to add 10000 different symbols into the cistercian symbol tables. Well, for maya, there are only 20 combinations for a symbol but since it is the 20-numeral system, the tool could do the calculation, which is not simply done by the symbol tables.

For braille or dancing man, you have no such complex symbol creation or calculation. You would not gain any benefit against the already existing tool.
