### ISSUE TITLE
Crash Center Point of Three Coordinates calculation

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#325]
App ist frozen, on calculation this point.
First point is N 48 42.53106 E 9 0.914352
![Screenshot_20210118-155902](https://user-images.githubusercontent.com/70719484/104931842-43647680-59a7-11eb-89b3-505045f5210b.jpg)

**Comment by S-Man42** [comment]
No crash, long calculating. Requires Cancel button!

**Comment by Mike-3** [comment]
Very long, no result after 15min. An immediate result with the GCC.

**Comment by S-Man42** [comment]
Done...

**Comment by S-Man42** [comment]
fix in e5ad98535a9f5bb80ffdfe5a3971cc4dbf3e8b8a
