### ISSUE TITLE
Layout ToDos in Knowledge-Base

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#329]
In the Knowledge-Base the following layout issues should be solved according the following examples
- dots from lists are missing --> solved
  - [symboltables](https://blog.gcwizard.net/manual/de/symboltabellen/01-welche-symboltabellen-stehen-zur-verfugung/)
- color of category boxes should be darker --> need more permissions to change style.css
  - [overview](https://blog.gcwizard.net/manual/de/)
  - [games](https://blog.gcwizard.net/manual/de/spiele/)
- color of the categories in the menu should be darker --> need more permissions to change style.css
  - [games](https://blog.gcwizard.net/manual/de/spiele/)
  - [scrabbble](https://blog.gcwizard.net/manual/de/scrabble/)
- 50% setting for the icons of coordinate functions are ignored --> need help
  - [waypoint projection](https://blog.gcwizard.net/manual/de/wegpunktprojektion-peilung/01-wie-funktioniert-die-wegpunktprojektion-peilung/)
- h3 should be orange --> need help
  - [multi decoder](https://blog.gcwizard.net/manual/de/allgemeine-codeloser/03-wie-funktioniert-der-multi-dekodierer/)

**Comment by S-Man42** [comment]
All done except the "50%" issue which I don't understand.

**Comment by Birdy2404** [comment]
dots from lists are missing
    https://blog.gcwizard.net/manual/de/symboltabellen/01-welche-symboltabellen-stehen-zur-verfugung/

**Comment by S-Man42** [comment]
Done.
