### ISSUE TITLE
List of postcode (PLZ) and prefix (Vorwahl)

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#338]
Not sure if worldwide lists for all towns / relevant countries are exisiting. 
https://de.wikipedia.org/wiki/Liste_der_Kfz-Nationalit%C3%A4tszeichen

Problem is 1:n (prefix : postcode)

Could be in a format like:
- [Countries](https://www.laendervorwahl.org/alle.php) (244)
  - Germany +49  D
  - Great Britain & Northern Ireland +44  GB
- [Germany](https://www.bundesnetzagentur.de/DE/Sachgebiete/Telekommunikation/Unternehmen_Institutionen/Nummerierung/Rufnummern/ONRufnr/ON_Einteilung_ONB/ON_ONB_ONKz_ONBGrenzen_node.html) (5200)
  - Berlin-Mitte 030  10115
  - Berlin-Mitte 030  10117
  - Berlin-Mitte 030  10119
  - ...
  - Bielefeld 0521 57080
- France
  - Paris ...

Also not sure if some of the lists will be changing over the months.

**Comment by Birdy2404** [comment]
[Vorwahl.xlsx](https://github.com/S-Man42/GCWizard/files/6371617/Vorwahl.xlsx)
@S-Man42 Can you please check out, if the data in the different cards are usable or if I need to  overwork the file?

**Comment by S-Man42** [comment]
Looks good. Can you put the EN strings into this structure:

```
"common_country_germany": "Germany",
"common_country_trinidadandtobago": "Trinidad and Tobago",
...
```

and then:

```
[
   {
      "name": "common_country_germany",
      "<washeißtvorwahlaufenglisch?>": ["+49"],
      "<undwasheißtländerkennzeichen?>": "D",
      "iso_country_code": "DE"
   }
]
```

Maybe we should think about the +1 numbers to split into their correct subnumbers:
+1 242 Bahamas
+1 403 Canada-Alberta
...
https://de.wikipedia.org/wiki/Nordamerikanischer_Nummerierungsplan

Because there are different numbers for same state, the list could be:

[
   {
      "name": "common_country_unitedstatesofamerica_wisconsin",
      "<washeißtvorwahlaufenglisch?>": ["+1 262", "+1 274", "+1 414", "+1 534", "+1 608", "+1 715", "+1 920"],
      "<undwasheißtländerkennzeichen?>": "US-WI",
      "iso_country_code": "US"
   }
]

**Comment by S-Man42** [comment]
Here you have not only the 2 letter ISO, but also the 3 letter ISO :) https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes

**Comment by Birdy2404** [comment]
Exchange/Symboltabellen/Cities
Exchange/Symboltabellen/Countries
Exchange/Symboltabellen/KFZ_DE
Everything is uploaded for the check

**Comment by S-Man42** [comment]
Added for Countries: 
ISO Codes
IOC Codes
Vehicle Registration Numbers
Calling Numbers

KFZ DE is too much effort atm as well as calling codes...

https://github.com/S-Man42/GCWizard/commit/77b1bcd23ef2c9faf00080be78cb310369db8fbe
