### ISSUE TITLE
Single Field for Reverse WIG format convertor 

### ISSUE THREAD

**Issue by capoaira** [S-Man42/GCWizard#363]
I would like a single field where it is possible to paste all three codes.
I'll try to do the changes. Which GCW widgets should I use for that?

**Comment by Mike-3** [comment]
The code is ready to be implemented so that all codes can be copied into the fields at once.

**Comment by S-Man42** [comment]
@capoaira I am not quite sure what you want to achieve:

If you want to input all three values with one click (as DEC/DMM/DMS), @Mike-3 already implemented something (which I already didn't have the time to test). But please feel free to checkout his branch and test it: https://github.com/S-Man42/GCWizard/pull/336

If you want to parse one string, the MultiDecoder can do this: It has only one input and can parse the WIG input into Coordinates.

Does this help?

**Comment by capoaira** [comment]
> If you want to parse one string, the MultiDecoder can do this: It has only one input and can parse the WIG input into Coordinates.

Yes I mean this in the coords converter. I did not know that this is possible in the MultiDecoder.
For me it was always annoying to paste three codes in three inputs instead of all three codes in one input. (Yes i know i'm lazy 😅)

> If you want to input all three values with one click (as DEC/DMM/DMS), @Mike-3 already implemented something

I don't know that there was already a Issue like this....

**Comment by capoaira** [comment]
I close this duplicate Issue...
