### ISSUE TITLE
Enhancing Search Engine

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#370]
The more tools and - even worse - languages we face, the bigger gets the search engine.

Currently it is implemented in a very naive way: Adding strings, put them into a string list (mapped on the relevant tool) and do a linear search on this for characters and strings.

The app now grew up: The search engine is getting much too big now, on slow devices the search engine might not work smoothly anymore.

Investigate a new approach, handling more search strings!

**Comment by ludoo0d0a** [comment]
I took this issue 

Step 1 : refactoring + index
Step 2 : async indexing at startup
Step 3 : try fuzzy search (for fun?)
Step 4 : use a database (may be not needed)

**Comment by S-Man42** [comment]
I assigned you ;) Please do this by yourself if you "grab" a ticket next time :)

Step 4: Please avoid using a database. We already used a SQLite DB in the past but this made some serious problems in the web version (that kind that for example the formula solver did not work anymore...).

**Comment by ludoo0d0a** [comment]
it seems first try give a ~ x10 ;)
from 0:00:00.006639
to.    0:00:00.000705

**Comment by ludoo0d0a** [comment]
Fixed also unnecessary rebuilds

anyway one rebuild remains on focus change
see https://github.com/flutter/flutter/issues/20607

We should investigate later.
