### ISSUE TITLE
Include MapCode into Coord-Formats

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#385]
https://www.mapcode.com/documentation?lang=de
für
https://coord.info/GC973DP

**Comment by S-Man42** [comment]
https://github.com/mapcode-foundation/mapcode-js

**Comment by S-Man42** [comment]
The most interesting part here is, that the MapCode might not be unique if you don't specify the entire territory. So we have to deal with numerous outputs in the converter now... It's definitely a challenge.

**Comment by ztNFny** [comment]
At least deciding should give only 1 result though and that's the more important part, isn't it? Would have needed this today 😉
