### ISSUE TITLE
feature: tool for calculating/checking check digits from ISBN, IMEI, IBAN, ...

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#403]
http://www.pruefziffernberechnung.de/
https://www.geldschein.at/euro-banknoten/euro_seriennummer.html

tools are
- check, if number is correct
- calculate missing digits

numbers should be
- IMEI
- IBAN
- ISBN
- ID from DE Personal IDCard
- Euro-Bill

**Comment by Mike-3** [comment]
Euro

**Comment by t-m-z** [comment]
https://www.geldschein.at/euro-banknoten/euro_seriennummer.html

**Comment by S-Man42** [comment]
Is this still in the pipeline for 2.0.0 or should we pospone it?

**Comment by t-m-z** [comment]
please postpone

Sent from MailDroid

-----Original Message-----

**Comment by t-m-z** [comment]
#635 is the same issue
