### ISSUE TITLE
Open File Dialog

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#407]
Insert an Open File Dialog:
- Should be adjustable for custom list of file types
- Should have an adjustable theme to fit our design
- Should work for iOS, Android (must have), Web: Nice to have

Use Cases:
- Images (Exif reader, Hidden zip container)
- Sound files (Frequency analysis for Morse, DTMF, ...)
- GPX/KML for Maps

**Comment by Mike-3** [comment]
a couple of the libs found 
flutter_file_dialog 2.0.0 only Android iOS
filepicker_windows 2.0.0 Android iOS Linux macOS Windows 
filesystem_picker 1.0.4 Android iOS Linux macOS Windows
documents_picker 1.0.0 only Android iOS
file_picker 3.0.0 for Android iOS web
file_access 1.0.3 Android iOS web

Overview
https://fluttergems.dev/file-picker/

open file and file save dialog would be good
