### ISSUE TITLE
Exif Reader

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#408]
Read exif information from images. My current favorite reader is http://exif.regex.info/exif.cgi

Requires #407

**Comment by ludoo0d0a** [comment]
possible options :
- https://pub.dev/packages/exif 
- https://github.com/gmpassos/image_metadata
- https://pub.dev/packages/exifdart

**Comment by S-Man42** [comment]
Please don't forget to add the thumbnail view, if exif data contains thumbnail, as the tool which linked above does... I often had mysteries where the thumbnail was a hint...

**Comment by S-Man42** [comment]
Maybe we should call the tool "metadata reader" instead of "exif reader". Then we can show as well:

- Thumbnails, Filesizes, Filedurations (animated gifs... try it out at the website), ...

**Comment by ludoo0d0a** [comment]
if we go in this, it will be a huge feature around file :
- file into hex
- bom parser
- exif
- file metadata
- ...

I prefer a section around file management, and keep tool easy to understand

**Comment by S-Man42** [comment]
That's my plan :)

**Comment by Mike-3** [comment]
https://coord.info/GC4P87Y
example for nested thumbnails

**Comment by ludoo0d0a** [comment]
I have an issue with gps data
then I will add file info on a 1st section
then all exif sections
and i need to extract and display thumbnails properly in it own section

**Comment by S-Man42** [comment]
GPS Data -> Show directly on map :)

**Comment by ludoo0d0a** [comment]
> GPS Data -> Show directly on map :)

Yeah, exactly the idea ! :)
or to go on conversion...
