### ISSUE TITLE
Detect hidden archives in files

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#412]
Sometimes image files are not only images, but also ZIP files. So you need to rename, e.g., .jpg into .zip and then you are able to open it as a zip file. It would be great to have tool which checks this automatically.

Of course, it would be great to be able to create such files, wouldn't it?

Requires #407

**Comment by S-Man42** [comment]
http://mroann.de/GC3BPHA/bg.jpg (Hidden ZIP File)

BTW: I like the presentation of the MysteryWizard which displays the "EXTRA BYTES".
![grafik](https://user-images.githubusercontent.com/16626063/117758269-035d2400-b222-11eb-90bd-d63002d79d03.png)

**Comment by ludoo0d0a** [comment]
done in exif_reader PR
https://github.com/ludoo0d0a/GCWizard/commit/c510d04694a278b14416d7f4a3e9ae40a2c0302f

and added filetype (BOM) as well

**Comment by ludoo0d0a** [comment]
done
