### ISSUE TITLE
mathmatic function solving quadratic equation

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#419]
https://coord.info/GC979RE

**Comment by S-Man42** [comment]
What recently came to my mind: We already embedded an extremely powerful mathematical engine (to one which solves the equations at the formula solver). Did you check if this library already provides all the mathematical stuff you are planning?

**Comment by t-m-z** [comment]
check. what is the name of this plugin to read the documentation.

Sent from MailDroid

-----Original Message-----
