### ISSUE TITLE
French Translations too long

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#422]
https://blog.gcwizard.net/wp-content/uploads/2021/03/formula_solver_fr_10.png
https://blog.gcwizard.net/wp-content/uploads/2021/03/formula_solver_fr_11.png

Hello @ludoo0d0a : Would be great, if you could have a look on that.
The french texts are a little bit oo long for the contexxt menu. Maybe we should have a linebreak or shorter texts?

**Comment by Birdy2404** [comment]
Further findings:
https://blog.gcwizard.net/wp-content/uploads/2021/03/open-map.png

**Comment by S-Man42** [comment]
Generally please much shorter texts if possible in any way. In these few cases a linebreak could do the job... (Hope so)

**Comment by ludoo0d0a** [comment]
@Birdy2404 , have you got the same issue on https://blog.gcwizard.net/wp-content/uploads/2021/03/formula_solver_fr_10.png
for all languages as well ? i don't know how to reduce in french ; and it should be the same in all langs, isn't it ?

**Comment by ludoo0d0a** [comment]
I checked 3 langs, fr is really longer than others. I used ellipsis. It should be ok (Ouvrir dans Coord. variables)

**Comment by ludoo0d0a** [comment]
> Further findings:
> https://blog.gcwizard.net/wp-content/uploads/2021/03/open-map.png

and for the map, I cannot reproduce (even with font size 23).

**Comment by Birdy2404** [comment]
> @Birdy2404 , have you got the same issue on https://blog.gcwizard.net/wp-content/uploads/2021/03/formula_solver_fr_10.png
> for all languages as well ? i don't know how to reduce in french ; and it should be the same in all langs, isn't it ?

yes got the same issue in Android Studio - Pixel 2 API 30 - 1080 x1920 420 dpi

**Comment by Birdy2404** [comment]
![Convertisseur_Energie_2](https://user-images.githubusercontent.com/34218281/113453559-89f23a80-9406-11eb-9775-0f86f2e92ea3.png)
![Convertisseur_Energie_1](https://user-images.githubusercontent.com/34218281/113453560-8a8ad100-9406-11eb-8e27-0248080e39cf.png)
@ludoo0d0a Please check, if you can rename the Energies

**Comment by Birdy2404** [comment]
![Humidite_vs_vent](https://user-images.githubusercontent.com/34218281/113455423-db9cc400-940a-11eb-93bd-1066657a816f.png)
Température apparente -> Refroidessement par le vent
Should be something with vent instead of humiditè

**Comment by ludoo0d0a** [comment]
Oups! Not yet done !

**Comment by S-Man42** [comment]
ok :)

**Comment by ludoo0d0a** [comment]
> ![Humidite_vs_vent](https://user-images.githubusercontent.com/34218281/113455423-db9cc400-940a-11eb-93bd-1066657a816f.png)
> Température apparente -> Refroidessement par le vent
> Description should be something with vent instead of humiditè

fixed

**Comment by ludoo0d0a** [comment]
> ![Convertisseur_Energie_2](https://user-images.githubusercontent.com/34218281/113453559-89f23a80-9406-11eb-9775-0f86f2e92ea3.png)
> ![Convertisseur_Energie_1](https://user-images.githubusercontent.com/34218281/113453560-8a8ad100-9406-11eb-8e27-0248080e39cf.png)
> @ludoo0d0a Please check, if you can rename the Energies

i translate into Cheval-vapeur. For text in fr, it's ok !!

in de, there is a missing translation
 "common_unit_power_hp_name": "Horsepower",  ==> Pferdestärke ??
  "common_unit_power_ps_name": "Pferdestärke", ==> metric Pferdestärke ??


and finally I'm not sure about the related unit (PS) :

I found that 1PS = 0.986hp
so horsepower can not in PS , isn't it ?

**Comment by S-Man42** [comment]
As you  said: Horsepower is not Pferdestärke ;) That's why there are two entries: Horsepower and Metric Horsepower (= Pferdestärke)

**Comment by ludoo0d0a** [comment]
> As you said: Horsepower is not Pferdestärke ;) That's why there are two entries: Horsepower and Metric Horsepower (= Pferdestärke)

ok , understood now ! i mixed everything ;)

**Comment by ludoo0d0a** [comment]
done !
can be closed
