### ISSUE TITLE
Formula Solver: accidental deletion of the formula

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#44]
The minus at the edge of the screen can lead to accidental deletion of the formula - please ask "Really delete". 

![Minus_Formula](https://user-images.githubusercontent.com/62543251/79137970-fd450b80-7db3-11ea-9d90-a05ec40e3f1d.jpg)

**Comment by S-Man42** [comment]
Done for Formulas and Favorites
