### ISSUE TITLE
Base91/Base122, Base58

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#460]
https://github.com/bwaldvogel/base91
https://github.com/kevinAlbs/Base122

**Comment by S-Man42** [comment]
Base 58 (Bitcoin)
https://de.wikipedia.org/wiki/Base58

**Comment by S-Man42** [comment]
@t-m-z I can image, that's an interesting task for you :)

**Comment by t-m-z** [comment]
Base58 done

**Comment by t-m-z** [comment]
Base91 done

**Comment by t-m-z** [comment]
Base122 seems to be tricky

**Comment by t-m-z** [comment]
Aunt Google leeds to Bas24 as an Automatic Teller Machine - I am lost ...

**Comment by t-m-z** [comment]
Tool was merged

**Comment by S-Man42** [comment]
![grafik](https://user-images.githubusercontent.com/16626063/154996502-b2fc5f5d-0ccf-4fa6-9dd3-eba8e49ad46d.png)

Entered a space....

**Comment by t-m-z** [comment]
this is tricky because spaces are not part of the alphabet.
I decided to replace all spaces with ''
Otherwise the widget should be adapted to the allowed alphabets for every Base

**Comment by t-m-z** [comment]
so the question is how to deal with an illegal input for decoding:
1. remove the illegal chars
2. return an empty string

**Comment by S-Man42** [comment]
1.
