### ISSUE TITLE
Additional languages

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#468]
If we support additional languages without having the manual topics, the fallback need to search for the headline in the en.json to find the corresponding english article.

So all languages could be activated here https://crowdin.com/project/gc-wizard
If nobody translates it, we would have it at 0% and it doesn't hurt anybody. But everybody has the chance to start directly with translating.

**Comment by S-Man42** [comment]
One thing hurts me: As we saw with Italian, we get empty files in our system in that case... Well.. I think we can live with that...

**Comment by S-Man42** [comment]
Created a bunch of languages which should cover 99,9999% of all geocachers... Have fun :D
