### ISSUE TITLE
Deeplinks in Web Version

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#469]
(from Mike M. via email)

Again there was the request for URLs to the tools. To make this even more interesting, the user asked for "prefilled" options by the URL 

> `https://gcwizard.net/#/coordinate_calculations/format_converter/Quadtree/DMS:DD°MM.MMM`

I investigated a bit:
It seems that there's now a way to achieve deep links natively (without any magic and plugin usage):

https://flutter.dev/docs/development/ui/navigation/deep-linking

It seems, we can use `Navigater.pushNamed` (https://api.flutter.dev/flutter/widgets/Navigator/pushNamed.html) which takes an `route `parameter. Currently we are using `Navigator.push()` to open a new tool widget. This `pushNamed` creates a callback to a `routes` handler in the main app, which seems to work as a centralized registry:
https://flutter.dev/docs/cookbook/navigation/named-routes

Well, moreover it seems to be possible to handle arguments. In that case the `pushNamed` creates a callback to a `onGeneratedRoute`. So, maybe there's way to use our own registry for that.
https://flutter.dev/docs/cookbook/navigation/navigate-with-arguments

With the second approach, I guess it might be possible to pass the requested options as URL or query parameter to the route, so that we can pre-select the options as the user expected above.

Further reading: https://sellsbrothers.com/understanding-flutter-deep-links-on-the-web

**Comment by Mike-3** [comment]
Which features should now be implemented in the first attempt of the web interface?
At the moment these features are implemented or in planning.
alphabetvalues
morse
coords converter
multidecoder

**Comment by Mike-3** [comment]
There will be many conflicts as a result of the refactoring. That's why I didn't want to include so many features at first.

**Comment by capoaira** [comment]
Is there are no way, to have for every feature a deeplink?

**Comment by S-Man42** [comment]
@capoaira There will be a deeplink for every tool, but at the first glance only a few tools will support input specific APIs.

So you will be able to call all features by URL but for some you will be able to fill the input fields and options by url query params

**Comment by S-Man42** [comment]
Deeplinks, a few thoughts :

1.) Please make all page names lowercase (or if possible not case sensitive).
2) Leave out the submit=ok. We should run by default if possible, without having to specify that extra
3.) The way from deep links to real web API... This would be the exciting part, where third party apps could really benefit, instead of just opening a web page
3a) Is it possible to simply return the calculated value as JSON instead of the web page call? That haste ne WebAPI
3b) If this works, we have to think about versioning the web interface, because we might change something, but at release the third apps haven't changed yet, but still need the old version.

**Comment by Mike-3** [comment]
At the moment every feature can be opened/ viewed via the web. But values can only be entered for the adapted features.

**Comment by capoaira** [comment]
> @capoaira There will be a deeplink for every tool, but at the first step only a few tools will support input specific APIs.
> 
> So you will be able to call all features by URL but for some you will be able to fill the input fields and options by url query params

Ah, ok. url query params are nice
I'm happy, that it's going on here.👍🏻


> Which features should now be implemented in the first attempt of the web interface?

I would add RotX to the list.



> 3a) Is it possible to simply return the calculated value as JSON instead of the web page call? That would create a real WebAPI

A Web API would be really nice

**Comment by Mike-3** [comment]
According to the documentation, something like this is possible, but I have no idea how it works at the moment.
If you happen to have a link to look up where the data should be sent that would be great.
But then we still have to add a json output to each web feature.

**Comment by S-Man42** [comment]
In my head is something like an additional query parameter:

mytool?return=json or return=ui

and if return=json we simply send a REST response (maybe via http lib)

**Comment by t-m-z** [comment]
Regarding REST - take care. This needs a servlet running on your server. We had this discussion already (WIG Analyzer).

Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
Are you quite sure? I never read this when Isearched for json based rest calls. They all just mentioned http package...

**Comment by t-m-z** [comment]
Yes. Someone has to answer the REST-call.
This is usually an Java-Servlet running on Tomcat.

Sent from MailDroid

-----Original Message-----

**Comment by Mike-3** [comment]
That's right, I can use the WIG Analyzer to see how you did it.

**Comment by t-m-z** [comment]
There is a subdirectory on github with the java code of the servlet.
The main question is, is Mark allowed to run a java servlet. This was the reason why I build an own server for the WIG Analyzer 

Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
Hm, in my opinion it should not be necessary. A server is only necessary IF you want to calculate something on a backend like you do with the WIG Analyzer (calling the unluac.jar). But here we have a different case imho... Normally you send an url incl. some params to the Flutter App (pure JavaScript in that case) answers with an HTML page which is rendered by the Browser. What should be different if you'll simply answer with a JSON text instead of HTML text?

**Comment by t-m-z** [comment]
As long as the renderer/browser get the data he expects there will be no difference.
However, we started the discussion with a REST response
As far as I understood REST a REST application has to meet several architecture principles. One of those principles is a Client-Server-Architecture.   
IMO the Clients uses http methods like get, post to interact with the targets ressource state. Hence the server provides his state or changes his state according to the http message.

**Comment by capoaira** [comment]
The pure js could be a problem for an real API, because it is executed on client side.
So if you send a request to the server it will return a, more or less, empty page.
You can test it if you press strg+U. Thats what a request gets as anwer. (You will see, it is the same for every tool)
The calculation is on client side, but a simple API request will not execute js.

**Comment by Mike-3** [comment]
a few parameter examples:

coords_formatconverter?input=N48%C2%B023.123%20E9%C2%B012.456&result=json 
return -> ["{\"format\":\"coords_dec\",\"label\":\"DEC: DD.DDD°\",\"output\":\"48.3853833333\\n009.2076\"}"]

coords_formatconverter?input=N48%C2%B023.123%20E9%C2%B012.456&toformat=coords_utm&result=json
return -> ["{\"format\":\"coords_utm\",\"label\":\"UTM\",\"output\":\"32 U 515370.3344 5359156.2432\"}"]

coords_formatconverter?input=N48%C2%B023.123%20E9%C2%B012.456&toformat=coords_all&result=json
return -> ["{\"format\":\"coords_dec\",\"label\":\"DEC: DD.DDD°\",\"output\":\"48.3853833333\\n009.2076\"}","{\"format\":\"coords_dmm\",\"label\":\"DMM: DD° MM.MMM'\",\"output\":\"N 48° 23.123'\\nE 009° 12.456'\"}","{\"format\":\"coords_dms\",\"label\":\"DMS: DD° MM' SS.SSS\\\"\",\"output\":\"N 48° 23' 07.380\\\"\\nE 009° 12' 27.360\\\"\"}","{\"format\":\"coords_utm\",\"label\":\"UTM\",\"output\":\"32 U 515370.3344 5359156.2432\"}","{\"format\":\"coords_mgrs\",\"label\":\"MGRS\",\"output\":\"32U NU 15370.3344 59156.2432\"}","{\"format\":\"coords_xyz\",\"label\":\"XYZ (ECEF)\",\"output\":\"X: 4189095.267168\\nY: 679055.634126\\nZ: 4745442.826329\"}","{\"format\":\"coords_swissgrid\",\"label\":\"SwissGrid (CH1903/LV03)\",\"output\":\"Y: 731056.6298229598\\nX: 360966.1884817833\"}","{\"format\":\"coords_swissgridplus\",\"label\":\"SwissGrid (CH1903+/LV95)\",\"output\":\"Y: 2731056.6298229597\\nX: 1360966.1884817833\"}","{\"format\":\"coords_gausskrueger\",\"label\":\"Gauß-Krüger\\nGK 1: DHDN 2001\",\"output\":\"R: 3515452.07094153\\nH: 5360860.560128583\"}","{\"format\":\"coords_lambert\",\"label\":\"Lambert (RGF)\\nLambert-93 (RGF93)\",\"output\":\"X: 1159119.9280877486\\nY: 6827509.9041015\"}","{\"format\":\"coords_dutchgrid\",\"label\":\"RD (Rijksdriehoeks, DutchGrid)\",\"output\":\"X: 438168.7367347115\\nY: 50824.430242923714\"}","{\"format\":\"coords_maidenhead\",\"label\":\"Maidenhead Locator (QTH)\",\"output\":\"JN48OJ42VL88VB19\"}","{\"format\":\"coords_mercator\",\"label\":\"Mercator\",\"output\":\"Y: 6171210.049860006\\nX: 1024985.3434281456\"}","{\"format\":\"coords_naturalareacode\",\"label\":\"Natural Area Code (NAC)\",\"output\":\"X: HR0K3000\\nY: R1WS6QGZ\"}","{\"format\":\"coords_openlocationcode\",\"label\":\"OpenLocationCode (OLC, PlusCode)\",\"output\":\"8FWF96P5+5256Q6\"}","{\"format\":\"coords_slippymap\",\"label\":\"Slippy Map Tiles\",\"output\":\"X: 538.1905066666667\\nY: 354.31275209098703\\nZoom: 10\"}","{\"format\":\"coords_reversewhereigo_waldmeister\",\"label\":\"Reverse Wherigo (Waldmeister)\",\"output\":\"823198\\n405007\\n867530\"}","{\"format\":\"coords_reversewhereigo_day1976\",\"label\":\"Reverse Wherigo (Day1976)\",\"output\":\"b98j8\\nlvccv\"}","{\"format\":\"coords_geohash\",\"label\":\"Geohash\",\"output\":\"u0we382c29hnjw\"}","{\"format\":\"coords_quadtree\",\"label\":\"Quadtree\",\"output\":\"1202211030021300001102010120001213033111\"}","{\"format\":\"coords_makaney\",\"label\":\"Makaney (MKC)\",\"output\":\"GXKS+ODDT\"}","{\"format\":\"coords_geohex\",\"label\":\"GeoHex\",\"output\":\"QD23033818514417353064\"}","{\"format\":\"coords_geo3x3\",\"label\":\"Geo3x3\",\"output\":\"E7188184626289938795\"}"]

rotation_general?input=test&parameter1=4&result=json
return -> {"output":"xiwx","outputreverse":"paop"}

alphabetvalues?input=Test

alphabetvalues?input=20%205%2019%2020&modeencode=true

Morse?input=...%20---%20...

Morse?input=test&modeencode=true

**Comment by S-Man42** [comment]
@t-m-z Well, in my understanding REST simply defines the interfaces as a standardized exchange format, not the part behind (of course there are some additional principles, but I've never seen a productive project which uses more from the quite theoretically original concept than the simple REST format for HTTP data exchange). It defines, how to talk with http interfaces. What happens after the interface layer, if there is a JS or real backend, is not relevant for the information exchange. 

Well, for less misunderstanding, don't call it REST. Just stay on HTTP layer. Currently we receive some sort of HTTP requests incl. URL params and they will be parsed correctly. In return the receiving JS sends a document, which accidentially can be interpreted as HTML. 

So my only idea is, to make the Flutter App (the JS) creating not necessarily a HTML text but a JSON text. In theory it shouldn't be a technically thing (HTTP is not interested in the specific data it transports) , more a question whether we can get Flutter support this. 

On the other side of the communication the calling instance now will receive some JSON data instead of a HTML code - next to HTTP status 200 code or something - and can do with it whatever it wants.

**Comment by S-Man42** [comment]
@Mike-3 Looks good for a first start. We should talk about naming nonetheless. But it's the next step. First we need to elaborate the way to achieve this technically

**Comment by S-Man42** [comment]
Edit: It wasn't clear to me, that Mike's examples are already running code! So, yeah, great, it seems he did the biggest step towards a web API! Congrats!

**Comment by S-Man42** [comment]
> The calculation is on client side, but a simple API request will not execute js.

Ah, that's the point I missed... argh... hmmmmm

**Comment by S-Man42** [comment]
Sorry guys. Of course @t-m-z and @capoaira are right. I had a Knoten in my Hirn. I missed the point that Flutter only provides a client side JS unfortunately and the cslling instances only receive the JS file, not the result.... And if this instance does not interpret the JS, of course, it cannot generate generate any result...

Mist.

**Comment by capoaira** [comment]
For #488 it can be enough. I could use an iframe and reading from it when the result were calculated. But any real application witch isn't possible to use such things like iframes, can't use the api.

**Comment by capoaira** [comment]
Moin, is it possible to add also the formula solver to the api/query params?
I would really like to give owners the possibility to provide the formulas in a Listing, so that the the Extension provide an UI for solving directly in the Browser.

**Comment by S-Man42** [comment]
Hi, do you have a concrete proposal how you want to handle it?

In principle I think we could do it. But first we need to get thr whole thing running again :D

**Comment by capoaira** [comment]
We need some way to send all variable and one (or all) formulas. Because that could be very long it may make sense to use a post request. But I'm not sure if that is possible. Otherwise we are limited by the maximal url length and have to encode the formula.
