### ISSUE TITLE
SwissGrid+ Bug

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#473]
insert current coordinates -> 6 digit number (SwissGrid Format) (SwissGrid+ correct with 7 digits)
outpout correct with 7 digits (SwissGrid+ to SwissGrid+).
insert manual 7 digits -> wrong output

**Comment by Mike-3** [comment]
I think the problem is the same widget for both formats. On paste LatLng coordinates no check for SwissGrid or SwissGrid+.

**Comment by S-Man42** [comment]
Yes, that was it.
