### ISSUE TITLE
Images: Animated Gifs - Show frames as gallery

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#481]
- Extract all frames, show as gallery, so one can switch with swipe or buttons to next and previous.
- Metadata: Link to Exif Tool, Show duration of each frame in ms

**Comment by S-Man42** [comment]
Example: 9 Frames:
25000ms, 25000ms, 25000ms, 1000ms, 1000ms, 1000ms, 5000ms, 1000ms, 1000ms

![Titelbild](https://user-images.githubusercontent.com/16626063/114732940-373c4b00-9d43-11eb-9b7c-5209b2168c6e.gif)

(http://exif.regex.info/exif.cgi extracts the frames when search for exif data; GIMP shows durations per frame)

**Comment by Mike-3** [comment]
I've already had the case that the time between the image changes resulted in the coordinates

**Comment by S-Man42** [comment]
Yes exactly that came to my mind

**Comment by S-Man42** [comment]
https://github.com/brendan-duncan/image

**Comment by Mike-3** [comment]
short Docu under //Exchenge/Animierte Bilder Kurzdoku.docx
