### ISSUE TITLE
Request: Catan code

### ISSUE THREAD

**Issue by ztNFny** [S-Man42/GCWizard#483]
Catan (aka Settlers of Catan) has cards assigning a letter to a number, can be used for a simple replacement cipher.

Here's the codes. It's unique only when you go from letter to number.
A5
B2
C6
D3
E8
F10
G9
H12
I11
J4
K8
L10
M9
N4
O5
P6
Q3
R11

**Comment by S-Man42** [comment]
Hahaha :D I confess, I just had to look at my boardgame to know what you meant :) 

Yes, it's no problem. I plan this for release 1.6.0

**Comment by S-Man42** [comment]
Correction: will be in the next release.

**Comment by S-Man42** [comment]
Done https://github.com/S-Man42/GCWizard/commit/cc909810fdf38c98d5e5c95ee369291b811c7391

(incl. the different values from the expansion set, of course)
