### ISSUE TITLE
feature: calculating the length of a shadow at given place and time

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#484]
https://www.geocaching.com/seek/cache_details.aspx?wp=GC6A0ZZ&title=peter-und-die-schattendiebe

input: coords, date, time
re-use of astronomy/sunposition to get altitude
output: length = height * cot(altitude)
            azimut
            altitude

this cache is also a good example for the file-tools

**Comment by S-Man42** [comment]
#565
