### ISSUE TITLE
Translation for Blog / Manual Links

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#486]
![grafik](https://user-images.githubusercontent.com/34218281/115100511-70d8a600-9f3d-11eb-915d-cf6ae9ed49a9.png)

Should those really be translated, or do we have a workarround to not use them, as long as the documents are not available

**Comment by S-Man42** [comment]
These are strings which need to be translated if necessary. But if there's no such website, take the en version or simply leave them. In that case:

a) Crowdin puts the EN version automatically to the lamg file
b) The tool takes the EN version automatically it string does not even appear in the lang file

**Comment by Birdy2404** [comment]
Sorry for the little missunderstanding. Those strings are at crowdin and will there be tranaslated by our users. Should they be hidden and we reffer initial to the english documents?
As soon as we have translations for this, we need to manually switch in the code.
But I have no idea, how it works and what will happen to french ;)

**Comment by S-Man42** [comment]
yes. hide them

**Comment by Birdy2404** [comment]
Strings are hidden
