### ISSUE TITLE
Manual: How to translate does not include crowdin

### ISSUE THREAD

**Issue by capoaira** [S-Man42/GCWizard#487]
The [blog post ](https://blog.gcwizard.net/manual/de/unterstutzen-beim-ubersetzen/03-wie-helfe-ich-beim-ubersetzen-der-gc-wizard-zeichenketten/) says that you need the json file for the translation of the gcw. But it makes more sense to add the crowd link.

**Comment by Birdy2404** [comment]
https://blog.gcwizard.net/manual/de/unterstutzen-beim-ubersetzen/03-wie-helfe-ich-beim-ubersetzen-der-gc-wizard-zeichenketten/
https://blog.gcwizard.net/manual/en/supporting-with-translations/03-how-do-i-help-translate-the-gc-wizard-strings/
https://blog.gcwizard.net/manual/fr/aider-a-la-traduction/03-comment-puis-je-aider-a-traduire-les-chaines-de-lassistant-gc/

Wurden alle 3 entsprechend neuer Vorgehensweise angepasst
