### ISSUE TITLE
IntegerTextInputFormatter needs reworking/explanation

### ISSUE THREAD

**Issue by dennistreysa** [S-Man42/GCWizard#5]
I tried to understand what's going on in the `formatEditUpdate` method of the class `IntegerTextInputFormatter`. The 'normal' mode seems to work properly, but list mode is somewhat broken, or at least I don't quite get it.

The following piece

```dart
newValue.text.split(regex).forEach((value) {
  if (!_checkIntegerValue(newValue.text))
    return oldValue;
});
```

does nothing. I guess the intention here was to return the old value back to the caller of `formatEditUpdate` which is not the case. Also `newValue.text` should be replaced by `value`I guess.

What is the intent here?

**Comment by S-Man42** [comment]
This should be discussed from beginning, since the development went on and any thoughts may be deprecated.

Please feel free to reopen it, if necessary
