### ISSUE TITLE
[PI number] get nth decimal 

### ISSUE THREAD

**Issue by ludoo0d0a** [S-Man42/GCWizard#554]
To provide a nth decimal to avoid to list the whole list (and iteration time)

Goal : to be able to access decimal up to 5 million (or even 50?..)
check speed efficiency...

some references:
https://web.archive.org/web/20150627225748/http://en.literateprograms.org/Pi_with_the_BBP_formula_%28Python%29
https://dev.to/anshul2910/finding-the-nth-digit-of-pi-3nhl

**Comment by ludoo0d0a** [comment]
dev.to article manage only 100k.
it failed if increase this limit up to 900k. :(

**Comment by S-Man42** [comment]
I guess, this can be closed here, right?
