### ISSUE TITLE
[New feature] Shadoks numbers

### ISSUE THREAD

**Issue by ludoo0d0a** [S-Man42/GCWizard#555]
Add a new tool to provide shadok numbers conversion

https://www.dcode.fr/numeration-shadok

(idea from daniel.b)

**Comment by t-m-z** [comment]
see PR - enhancement for Numeral Words
graphical encoding/decoding is ongoing

**Comment by S-Man42** [comment]
https://github.com/S-Man42/GCWizard/pull/567
