### ISSUE TITLE
[enhancement] display symbols selection

### ISSUE THREAD

**Issue by ludoo0d0a** [S-Man42/GCWizard#556]
Display preview of selection as symbols with decrypted text when using symbols

when creating mystery, owner can store easily screenshot of question+answer.

![symbol preview selection](https://user-images.githubusercontent.com/294090/118890228-9f5fed00-b8fe-11eb-9b2b-4216da65451f.jpg)

(idea from daniel.b)

**Comment by S-Man42** [comment]
Whats the difference to "encryption"?

**Comment by S-Man42** [comment]
any news here?
