### ISSUE TITLE
Operation formula solver - variable coordinates 

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#579]
Doesn't it make sense to transfer the operation and functionalities of the form solver to the variable coordinate as well?
(Context menu -> export, import, modify)

**Comment by S-Man42** [comment]
I didn't want to make the VarCoords a second Formula Solver. It makes more sense to discuss a better general concept concerning VarCoords <-> Formula Solver...

Indeed, recently needed a VarCoords function for non-coords formulas. I think, a complete restructuring makes sense, but this should be discussed in deep and it's a bunch of work

**Comment by Mike-3** [comment]
I had more in mind to bring the functionality and operation from the Formula Solver to VarCoords.

**Comment by S-Man42** [comment]
Yes I understood :) But this I want to avoid if possible. I see the neccessarity but I want to avoid to duplicate the formula solver tool and its functions. Instead, to make it clearer, a concept for a better workflow, maybe a more common tool, should be thought of...
