### ISSUE TITLE
textToIntList needs reworking.

### ISSUE THREAD

**Issue by dennistreysa** [S-Man42/GCWizard#6]
`textToIntList` in common_utils.dart lookes somewhat complicated to me. Instead of using a replace approach, I would suggest an extraction approach by the following code:

```dart
List<int> textToIntList(String text, {bool allowNegativeValues: false}) {
  if ((text == null) || (allowNegativeValues == null))
    return [];
      
  final regex = allowNegativeValues ? RegExp(r'-?\d+') : RegExp(r'\d+');
  
  return regex.allMatches(text).map((value) => int.tryParse(text.substring(value.start, value.end))).toList();
}
```

That also eliminates the edge case of a straying '-'.

**Comment by S-Man42** [comment]
Hm, to be honest: For me, this approach looks just as complicated to me as mine or vice versa... I see neither advantages for yours nor for mine. So, it's not clear to me, why you would change this. Can you explain it? :)

**Comment by dennistreysa** [comment]
I find it more convenient to have a RegEx that is "extracting what I'm looking for" and not "throwing away what I'm NOT looking for", especially when the method implies that by it's naming.
The opposite may apply to special "cleaner"-methods like "removeNonAlpha" etc.

Regarding your objection, that this will break the user being able to insert negative values:

The `GCWIntegerListTextField` currently does not remove any chars on it's own, so no worries, but I'm not sure if this really was the intent.

I think the real problem is the interaction between `textToIntList` `GCWIntegerListTextField` and `IntegerTextInputFormatter`.

Which makes this Issue related to #5 

So, my idea here is the following:

`textToIntList` shall extract only valid numbers (like in my code above)
`IntegerTextInputFormatter` shall accept anything that could become a valid number (similar to your 
textToIntList) and filter out everything else.

Which in return means "1 - -2 -   3" is a valid input, but shall be parsed to [1, -2, 3] or [1, -2, -3] (I leave that to you, but would go with second).

Which leads me to another problem. What if the user copies and pastes a list that looks like the following: "1, 2, 3, 4" (which looks like a valid, parsable integer list to me).

As far as I understood the code, the input formatter would fall back to the original string and one would not be able to paste such a string (because of the commas).

I guess the solution here is to return a new filtered string instead of just the old one.

**Comment by S-Man42** [comment]
This should be discussed from beginning, since the development went on and any thoughts may be deprecated.

Please feel free to reopen it, if necessary
