### ISSUE TITLE
Exif Viewer: Loading image can take several seconds -> Progress Indicator

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#600]
Loading image can take several seconds.

I am not quite sure why loading exif data takes time. Maybe you could optimize the file open process? Otherwise add a Progress Indicator.

**Comment by ludoo0d0a** [comment]
do you have a sample ?
I never see a lag on loading.
but yes may be some huge image can be delayed.

**Comment by S-Man42** [comment]
Take the image from #601

**Comment by S-Man42** [comment]
I guess, not necessary at the moment...
