### ISSUE TITLE
Barcode Creator: Bars instead of Pixels

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#605]
When entering a 01010100010011001 the result is only one pixel high. It makes sense to generate longer bars instead of only a pixel, when input has only one dimension.

If framework doesnt work for that, the workaround could be to duplicate the input internally:

01001001 -> 

internal:
01001001
01001001
01001001
01001001

-> image creator

Pseudocode for that could be:
instead:

createBarcode(input)

-->
createBarcode((input + '\n') * 10)

**Comment by Mike-3** [comment]
I am mit so happy, that we "manipulate" the input, but I change this ;-).
