### ISSUE TITLE
Check digits: calculate check digits, check number, calculate missing digits

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#635]
- ISBN
- EAN
- IBAN
- DE ID Card
- DE Tax ID
- IMEI
- EURO

http://www.pruefziffernberechnung.de/
https://www.geldschein.at/euro-banknoten/euro_seriennummer.html

**Comment by Birdy2404** [comment]
Example for IBAN: https://coord.info/GC6B1BE

**Comment by Mike-3** [comment]
Example for Euro: http://coord.info/GC6W1DW

**Comment by t-m-z** [comment]
UIC Railway wagon numbers https://de.wikipedia.org/wiki/UIC-Wagennummer#Beispiel_UIC-Entschl%C3%BCsselung
