### ISSUE TITLE
[Sudoku] Find all solutions

### ISSUE THREAD

**Issue by capoaira** [S-Man42/GCWizard#643]
Today I tried to solve a Sudoku cache, but the solver only show one solution (of 332)
Maybe it would be possible to show all solutions or give a hint, that there are more than one solutions.
My example: [GC8YWM4 ](https://coord.info/GC8YWM4) (solved with https://www.surfpoeten.de/apps/sudoku/solver/)

**Comment by capoaira** [comment]
Maybe https://pub.dev/packages/sudoku_solver_generator/ helps. Looks like it had the method `.hasUniqueSolution()`

**Comment by S-Man42** [comment]
Well, this feature is frequently requested... Beside the fact that I dont know if my code can manage this, I am really wondering if this is a good thing for solving Geocaching Mysteries... To be honest, of an owner shows you a Sudoku and expects that you solve it 300 different ways,... really it's no mystery anymore. The mystery is trash. No more no less.

**Comment by capoaira** [comment]
> really it's no mystery anymore. The mystery is trash. No more no less.

I agree. But it is always possible, that an owner not check if there are more than one solution. It is good to check this in the GCW. I need some time to realized, that there are more solutions.

My example is extreme, but probably not the only one.

Off-topic: If you find the right sudoku solution of my example, you have solved 88 Mysterys ;)

**Comment by capoaira** [comment]
> really it's no mystery anymore. The mystery is trash. No more no less.

I agree. But it is always possible, that an owner not check if there are more than one solution. It is good to check this in the GCW. I needed some time to realized, that there are more solutions.

My example is extreme, but probably not the only one.
 
Off-topic: If you find the right sudoku solution of my example, you have solved 88 Mysterys ;)
