### ISSUE TITLE
Binary2Image: Throws Exception

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#650]
When using the function, it throws an exception:
```

W/System.err( 8022): com.google.zxing.NotFoundException
E/flutter ( 8022): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: FormatException: Invalid envelope
E/flutter ( 8022): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:599:7)
E/flutter ( 8022): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter ( 8022): <asynchronous suspension>
E/flutter ( 8022): #2      scanBytes (package:qrscan/qrscan.dart:27:10)
E/flutter ( 8022): <asynchronous suspension>
E/flutter ( 8022): 
```

Recognized it in the new Karel function from @t-m-z  It seems that the input always checks for a QR code, even if not intended.

So, please decouple the simple "drawing function" from the "barcode check".

**Comment by S-Man42** [comment]
BTW: Is the name still fitting? It's not longer "binary", isn't it?

**Comment by Mike-3** [comment]
This exception comes from the library, which is examining the image for the QR code. I haven't found a way to suppress this. It is "just" an internal exception. It is always triggered if no barcode was recognized.

**Comment by Mike-3** [comment]
> BTW: Is the name still fitting? It's not longer "binary", isn't it?

Why not ? Binary only stands for black and white images. At least that was my interpretation.
But I also have no idea for a better / more meaningful name.

**Comment by S-Man42** [comment]
Bur why should @t-m-z check for a barcode. He just wants to create an image. Using the painting function should not automatically trigger the qr reader.

if it is a common exception, it should be catched. I once had the case that Google didnt allow the version upgrade because they found uncatched exceptions

**Comment by Mike-3** [comment]
```
scanBytes(_outDecodeData).then((value) {
          setState(() {
            _codeDecodeData = value;
          });
        });
```

qr code call in karol robot widget

**Comment by S-Man42** [comment]
#651

**Comment by S-Man42** [comment]
Still existing (Binary To Image Tool)

**Comment by S-Man42** [comment]
Everything ok here?

**Comment by Mike-3** [comment]
From my side it is ok.
