### ISSUE TITLE
Recycling codes

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#672]
Request by Facebook:
Jedes Recyclingprodukt hat eine Nummer (siehe Tabelle): https://de.wikipedia.org/wiki/Recycling-Code
http://www.gesetze-im-internet.de/verpackg/anlage_5.html
https://de.wikipedia.org/wiki/Recycling-Code und deren Übersetzungen (da, en, hu, nl, pl, zh)

**Comment by Birdy2404** [comment]
[de.txt](https://github.com/S-Man42/GCWizard/files/6979085/de.txt)
[en.txt](https://github.com/S-Man42/GCWizard/files/6979086/en.txt)
[hu.txt](https://github.com/S-Man42/GCWizard/files/6979087/hu.txt)
[nl.txt](https://github.com/S-Man42/GCWizard/files/6979088/nl.txt)
[pl.txt](https://github.com/S-Man42/GCWizard/files/6979089/pl.txt)
[zh.txt](https://github.com/S-Man42/GCWizard/files/6979090/zh.txt)
[config.json.txt](https://github.com/S-Man42/GCWizard/files/6979091/config.json.txt)
[da.txt](https://github.com/S-Man42/GCWizard/files/6979092/da.txt)


Some lines are not translated in all languages, because they seems to not using it. 
If this is a problem, i will manually merge it into crowdin after the english strings are available there

Number 9 is used as ABS and Alkaline battery so I made a 9a for the ABS as the battery is used more often as 9.
I hope this is fine.

**Comment by S-Man42** [comment]
I wouldnt make it as 9a, if it is used as 9. So, if so, then we'd have 9 twice, which is ok for me. In the data of course we can keep it that way to make it unique. But we should display "9", not "9a"

**Comment by Birdy2404** [comment]
9 twice instad of 9a would be fine for me. But I have no idea, what is the necessary change in the config.json.

**Comment by S-Man42** [comment]
https://github.com/S-Man42/GCWizard/commit/104aad8e0c203225e2bd67dc8b141811ccfec47b
