### ISSUE TITLE
Edelcrantz Code

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#681]
Optical Telegraph. Can be build as a 3x3 rectangle matrix: (On/Off) using the segment display view

https://en.wikipedia.org/wiki/Telegraph_code#Edelcrantz_code

**Comment by t-m-z** [comment]
Nice idea - there are a lot of additional symbol tables which also could be considered.

However, there is a second point:
Edelcrantz developed a Code book which could be considered to - if we get a grip on this
https://trepo.tuni.fi/bitstream/handle/10024/102557/1513599679.pdf?sequence=1&isAllowed=y
page 23: Figure 2. Excerpt from an original codebook (adapted from [Tahvanainen, 1994]).
Appendix 1: Code book

**Comment by t-m-z** [comment]
https://archive.org/details/earlyhistoryofda0000holz/page/180/mode/2up

**Comment by t-m-z** [comment]
Main challenge is to get the codebook version from 1809 with the 10th shutter.

Besides this everything is fine

![Screenshot_1631396488](https://user-images.githubusercontent.com/2946628/132962269-216380bd-b8ac-4b03-9a45-d71742519994.png)

![Screenshot_1631396406](https://user-images.githubusercontent.com/2946628/132962249-92da42d3-f9db-4bc9-9236-8b661f89e53b.png)

![Screenshot_1631396422](https://user-images.githubusercontent.com/2946628/132962255-a6c48d58-a692-4346-8f41-dafdb7c9632f.png)

**Comment by t-m-z** [comment]
[edelcrantz-codebook.pdf](https://github.com/S-Man42/GCWizard/files/7149155/edelcrantz-codebook.pdf)

**Comment by t-m-z** [comment]
almost done

**Comment by t-m-z** [comment]
will be part of 2.1.0
