### ISSUE TITLE
Avatar Na'vi Code

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#708]
Evtl. as numeral words?
nefä puvol° mrrvomun.mezam mevohin | skien volaw° kew.vozam mezam mune

https://james-camerons-avatar.fandom.com/de/wiki/Oktale_Arithmetik --> explaning the numeral system

https://learnnavi.org/navi-vocabulary/ --> Für Richtung
- nefä=up (N)
- nekll=down (S)
- skien=right (E)
- ftär=left (W)

https://learnnavi.org/navi-numbers/ --> Countercheck

One of the caches to solve:
https://www.geocaching.com/geocache/GC5MJ89_hilfe-mein-navi-ist-kaputt

**Comment by t-m-z** [comment]
![Screenshot_1630703110](https://user-images.githubusercontent.com/2946628/132065292-4730a91d-d26a-4b59-abc1-d8b6335387ac.png)

**Comment by t-m-z** [comment]
![Screenshot_1630703127](https://user-images.githubusercontent.com/2946628/132065317-b6edcff2-e4c4-4955-93ac-fff52cee9c3d.png)

**Comment by t-m-z** [comment]
![Screenshot_1630703237](https://user-images.githubusercontent.com/2946628/132065379-8b1e4cc4-ad42-4520-aa3b-e3dd1e4c4e70.png)

**Comment by Birdy2404** [comment]
> 
> 
> ![Screenshot_1630703110](https://user-images.githubusercontent.com/2946628/132065292-4730a91d-d26a-4b59-abc1-d8b6335387ac.png)

shouldn't mrrvomun be 42 (5*8+2)
the other results for the coordinate are okay.
May a space would be fine to differ the numbers in 512 128 2

**Comment by t-m-z** [comment]
probably a lite nite typo. will check.
spaces are still a point - it is a general discussion to have spaces or not

Sent from MailDroid

-----Original Message-----

**Comment by Birdy2404** [comment]
In my personal opinion it's easier to put texts together than to seperate them.
