### ISSUE TITLE
Conways Game of Life

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#710]
Well, I sometimes though about implementing it. It's always kind of fun. Now I had a mystery to use it: GC68F1F

I saw the implementation from dcode.fr:
https://www.dcode.fr/game-of-life

I really like the options of this implementation and I believe I could be done the similar way. I'd add the option: "Without borders", so that the world wraps around (when leaving bottom it come to top). The only we should thing of properly is: What happens when it leaves at the corners diagonally. I am not quite sure atm whether it's a problem or not...

Maybe add some advanced options for
- Showing special figures: https://de.wikipedia.org/wiki/Conways_Spiel_des_Lebens#Die_Objekte
- Adding special rules and their figures: https://de.wikipedia.org/wiki/Conways_Spiel_des_Lebens#Abweichende_Regeln

What about exporting animated gifs?

**Comment by Mike-3** [comment]
example: GC1V6YN
