### ISSUE TITLE
Lychrel-Zahl for number sequences?

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#717]
[Wikipedia](https://de.wikipedia.org/wiki/Lychrel-Zahl)

[Cache](https://coord.info/GC9F97D)

**Comment by t-m-z** [comment]
https://www.dcode.fr/lychrel-number
https://oeis.org/A023108

because there is no algorithm according to wikipedia I will implement a list of the 249 already proved candidates.

**Comment by S-Man42** [comment]
#719
