### ISSUE TITLE
Red screen when transfering a single image from animated gif to Exif-/Metadata

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#720]
Open an animated gif and export a singe picture to show Exif-Metadata causes a red screen.
![Screenshot_1630864939](https://user-images.githubusercontent.com/2946628/132136886-b5e85312-f8b6-49b9-bef2-28f74e939bef.png)

**Comment by S-Man42** [comment]
GC5R2MY Jetzt bloß keine hohen Wellen schlagen (Unknown Cache) in Thüringen, Germany created by ___Bex___ - https://www.geocaching.com/seek/cache_details.aspx?guid=c98e8ad2-02e4-455c-a5a8-f412f7355a3a

**Comment by S-Man42** [comment]
Interesting... Frame 9 and 10 work...

**Comment by S-Man42** [comment]
s-man42.de/homer.gif

Some frame don't work as well.
