### ISSUE TITLE
generated QR Code can't be decoded

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#726]
![QR_de_02](https://user-images.githubusercontent.com/34218281/132971323-39096038-c88f-431d-91c2-23c24f2f8526.png)
![QR_de_01](https://user-images.githubusercontent.com/34218281/132971324-eb9b513f-d57a-4c2a-817d-0db1aa57a7fe.png)
The QR code for "https://gcwizard.net" was generated with our QR-Code generator and saved.
Encryption didn't recognice the code.

**Comment by S-Man42** [comment]
QR lib is gonna be changed due to issue #723
