### ISSUE TITLE
Space arround color correction missing

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#727]
Design-topic: If you compare both screenshots the QR-function has a surrounding space, so it doesn't look pressed into the frame.
The color correction uses the complete screen. I personally prefer the surrounding space.
Second topic: Can the open in "color correction" be suppressed, if you're already in the color correction?

![color_correction_de_01](https://user-images.githubusercontent.com/34218281/132971885-db0990b7-0191-4bb6-8b17-a6fb7cae8e6f.png)
![QR_en_02](https://user-images.githubusercontent.com/34218281/132971887-7f944921-e04c-4a8f-ad6b-c809dc5515ae.png)

**Comment by S-Man42** [comment]
Completely different technologies. The Image Viewer widget can be zoomed and all.. Itvs necessary to see as much as possible from the image...

**Comment by Birdy2404** [comment]
Reopened after Chat
