### ISSUE TITLE
French translation too long

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#728]
![File_open_in](https://user-images.githubusercontent.com/34218281/132972126-11732c2f-4a23-4e3d-aabc-e0ef96d81b72.png)

**Comment by ludoo0d0a** [comment]
I can name them without the verb "ouvrir" (open) like  "vue metadata", "vue hexa"... But you still get the same problem for other languages..and different resolution screen...

**Comment by Birdy2404** [comment]
We need the max. amount of characters, which are allowed, so we can set this at Crowdin at ath string in the context area
![context](https://user-images.githubusercontent.com/34218281/132983663-c7561114-75d2-4616-8af3-32e2df0dd896.png)

**Comment by Birdy2404** [comment]
Is it possible to find those "violations" automatically, so we can go through the strings and set the limit?

**Comment by Birdy2404** [comment]
![grafik](https://user-images.githubusercontent.com/34218281/135707784-96e6ffbd-ecc0-476c-8755-8f0c0ce68e57.png)

**Comment by Birdy2404** [comment]
Formula solver: Delete all formulas
A RenderFlex overflowed by 1.00 pixels on the right.

![formulasolver](https://user-images.githubusercontent.com/34218281/136889230-37f5d2b5-9381-4df0-9ac6-33c328bb7155.png)

**Comment by S-Man42** [comment]
Can i close this? Is anybody still watching this?

**Comment by Birdy2404** [comment]
I had the hope, that @ludoo0d0a will have a look on them.

**Comment by Birdy2404** [comment]
Hello @Mike-3,
would you like to check, if it is possible to make a line break, if the texts/translations are too long? See e.g. "Animated Images" in French, after you have chosen a file and want to export the output.

**Comment by Mike-3** [comment]
![image](https://github.com/user-attachments/assets/6355730e-9484-45bc-8b46-fb11490c7c9e)
