### ISSUE TITLE
Sorting of EXIF-Data

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#729]
https://www.geocaching.com/geocache/GC2Q337
https://s3.amazonaws.com/gs-geo-images/0daf625e-30bf-4b48-86c6-9de7c493ba08.jpg

https://www.geocaching.com/geocache/GCVEVX
https://s3.amazonaws.com/gs-geo-images/327853e4-7524-4320-8b71-52297e54d1ca_l.jpg

Should some EXIF-Data have more prio? Maybe compared with Mystery-Wizard?
E.g. UserComment, Model,...

**Comment by S-Man42** [comment]
There is still much slace for improvement at the Exif tool, but this is a point I really don't agree with. You can put relevant information into literally every section and even create your own section. It is absolute bit decidable with one should be preferred over another...

**Comment by Birdy2404** [comment]
okay, fine for me :-)
