### ISSUE TITLE
Deactivate foreign Search Strings

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#746]
As a German user you don't need the French or Korean search strings. So, to increase the search performance you should not add them to the search index.

Search index should include
- search common
- search en
- search [your locale] (if available)

link #370

**Comment by S-Man42** [comment]
For this:

1. Convert SEARCHSTRING files from 

searchstrings_commons.dart

`const SEARCHSTRING_MYSTRING = "...";`

to

searchstrings_commons.json:

```
{
   "mystring" = "...",
}
```

2. In registry replace `[SEARCHSTRING_COMMON_MYSTRING1, SEARCHSTRING_EN_MYSTRING1, SEARCHSTRING_DE_MYSTRING1, SEARCHSTRING_COMMON_MYSTRING2, ...]` with simple` ["mystring1", "mystring2"]`
3. In gcw_tools for creating search engine you recognize relevant JSON files:

searchstrings_commons.json
searchstrings_en.json
searchstrings_<mylocale>.json

Bonus: 
. The searchstrings JSON files can be used in Crowdin for translation. ;)
. The registry does not grow when new languages are added

**Comment by Birdy2404** [comment]
Will the search-strings be available at Crowdin soon?

**Comment by S-Man42** [comment]
I am planning to do this, but not in the next few weeks
