### ISSUE TITLE
GPX Import: Support <name> and <desc> tags for name

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#796]
For example from flopp export

**Comment by Mike-3** [comment]
desc is in the moment supported
wpt.markerText = xmlElement.getElement('desc')?.innerText;
We have only 'markerText' for a point. Add we 'desc' or 'name' in this entry? Or we add both ?

**Comment by S-Man42** [comment]
For import we should support both but only one.

markerText = gpx.name ?? gpx.desc

(or other way round. depends on the specification: I guess "name" is thought as title (=markerText), so this should be preferred over "desc")

**Comment by S-Man42** [comment]
For export, it's more tricky I guess. If name is title, we should use name. However, if GPX from Groundspeak (mis)uses desc for it, our result will differ from a GS gpx.

Although I always prefer to stay with standard, here we should think about the expectation.

**Comment by Mike-3** [comment]
[markers-1.zip](https://github.com/S-Man42/GCWizard/files/7552596/markers-1.zip)
flopp export file as zip.
gpx from github not supported.
