### ISSUE TITLE
Crash in Brainfuck interpreter

### ISSUE THREAD

**Issue by dennistreysa** [S-Man42/GCWizard#8]
When I try to open the Brainfuck interpreter, the App crashes with `The method 'call' was called on null.`  in
`BrainfkState._calculateOutput (package:gc_wizard/widgets/tools/encodings/brainfk/brainfk.dart:85:23)`

My guess is that `widget.interpret` is never set properly.

**Comment by S-Man42** [comment]
Fixed in https://github.com/S-Man42/GCWizard/commit/ef0cd485c805c4aea7b01c2624d8ead12f3101fc
