### ISSUE TITLE
IP Code (Schutzklassen)

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#800]
https://de.wikipedia.org/wiki/Schutzart

**Comment by Birdy2404** [comment]
Structure similar to resistance calculator?
![Screenshot_20211123-061833.png](https://user-images.githubusercontent.com/34218281/142974813-231d83e0-fe60-440e-91cc-88ed8a7a6dcd.png)

**Comment by S-Man42** [comment]
yes, why not
