### ISSUE TITLE
Piet (Esoteric programming language)

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#805]
Example: GC3JKKQ

**Comment by S-Man42** [comment]
The most complicated thing is the input widget, I guess.

In my opinion, it makes sense to offer a pad with colored buttons and an Enter button.

Funfact: My own geocache had nearly the same GC Code, so first I wondered, what my cache has to do with piet... :D

**Comment by Mike-3** [comment]
I actually think that the output with binary2image (like karol) is not the problem.
When reading in you have to get the number of rasters and then determine the color value of the respective raster.
With even codes, this should be quite feasible. The cropping on pictures is kind of like the symbol_replacer.
