### ISSUE TITLE
Symbol table weather data

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#806]
![weather](https://user-images.githubusercontent.com/34218281/143532854-eb6ae4e2-8eaa-4c3a-89b2-777cf828f089.png)

[Wearther data](https://www.dwd.de/DE/wetter/thema_des_tages/2016/2/7_Bild.png)
[All symbols](https://cdn2.hubspot.net/hubfs/604407/weather_symbols.gif)

Similar to geocache attributes:
- symbol table with numbers
- symbol table with meanings
meanings see here: https://www.wetterdienst.de/maps/topics/WeatherSymbols.gif

**Comment by AndyPuma** [comment]
bei den unter "All symbols" verlinkten ist auch die im GCW zu findenden doppelten Symbole dabei  93, 94, 95 , 97
