### ISSUE TITLE
TYPO: in german language de.json

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#81]
Verschlüsselung basierend **auch** einem Quadrat

https://github.com/S-Man42/GCWizard/blob/2d8fc0fa4904188362dd65b027df3370081118ad/assets/i18n/de.json#L752

THX sucher1202 per WhatsApp

**Comment by capoaira** [comment]
Ich kann noch etwas hinzufügen:

https://github.com/S-Man42/GCWizard/blob/2d8fc0fa4904188362dd65b027df3370081118ad/assets/i18n/de.json#L1015

**Comment by S-Man42** [comment]
Closed with Commit https://github.com/S-Man42/GCWizard/commit/a0072a84a9f9bb81b4a6fa79210f45988c1293f9
