### ISSUE TITLE
Feature request: Schwerpunkt von 3 Koordinaten (nicht: Umkreis-Mittelpunkt)

### ISSUE THREAD

**Issue by huberteff** [S-Man42/GCWizard#831]
Hallo, 
bei https://www.geocaching.com/geocache/GC797X9_drei-paparazzi wird der Schwerpunkt von 3 Koordinaten gebraucht. Das ist nicht der Umkreis-Middelpunkt. 
Webseite zum Bezeichnen: http://gps-cache.de/geocaching/koordinaten-peilung.htm
im Punkt "Gemittelter Schwerpunkt mehrerer Koordinaten".

**Comment by S-Man42** [comment]
Hi, schau mal unter Centroid (Arithmetisches Mittel). Das müsste das sein, was du suchst, oder?

**Comment by huberteff** [comment]
Hallo, ja das ist das was ich suche. Unter dem Namen waere ich allerdings nie drauf gekommen... vielleicht kann man die Suchfunktion irgendwie Tunen dass es bei "3 Punkte" das auch anzeigt?

**Comment by S-Man42** [comment]
Ist schon nachgerüstet, wird schnell mit erstellt :)
