### ISSUE TITLE
BUG - Symbol Table Baudot is wrong. 

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#835]
The symbols seems to derived from the table shown an https://de.wikipedia.org/wiki/Baudot-Code.
If you compare the above table with the table at https://en.wikipedia.org/wiki/Baudot_code you will see, that
a is 1 in decimal, hence encoded as 000-01 and not as 00-100
We should rename the wrong table and provide the correct table

**Comment by S-Man42** [comment]
dont hesitate :D

**Comment by t-m-z** [comment]
I am already working on it - but this means also to check ccitt1 ...

Sent from MailDroid

-----Original Message-----

**Comment by t-m-z** [comment]
see https://en.wikipedia.org/wiki/Baudot_code#/media/File:Baudot_Code_-_from_1888_patent.png
