### ISSUE TITLE
improvement: Formatkonvertierung CH1903

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#868]
![2022-01-09 11_55_52-Window](https://user-images.githubusercontent.com/62543251/148679437-304df8d2-875d-4ca2-bc50-7c355c193887.png)

Die Bezeichnung Ost/Nord ist konsistent zur Ausgabe  Y/X  Vorschlag: Y(Ost) / X(Nord)

**Comment by Birdy2404** [comment]
Crowdin is also changed in all translated languages
