### ISSUE TITLE
Add x meters from my location without entering degrees to Menu

### ISSUE THREAD

**Issue by Icebird2000** [S-Man42/GCWizard#869]
Is it possible to add a Menuoption to Coordinate Calculation mostly the same as Waypoint Projection but without the degrees. 
Show a circle on the map with x meters distance. 

In a GC is one task to walk the way 342 m from your actual position.

**Comment by AndyPuma** [comment]
Hi Icebird2000,

have you ever looked at Open Map? There you can create points and give them
a radius.

Greetings Andy

Icebird2000 ***@***.***> schrieb am So., 9. Jan. 2022, 18:55:

**Comment by S-Man42** [comment]
Hi, as @AndyPuma correctl said, this is actually possible:

Open Map > set map to your position with the button on the right side > (click button again if you dont want to see your own position, the map is still at your position) > click "Set point" on left side, which sets point to current position > click point > edit > set has circle > set distance > go back to map.


https://user-images.githubusercontent.com/16626063/148695602-c4a18877-ea63-4bf3-90b1-f334048026cf.mp4
