### ISSUE TITLE
Add serchstrings to crowdin

### ISSUE THREAD

**Issue by Birdy2404** [S-Man42/GCWizard#873]
- Add searchstrings to Crowdin
- Check if also the titles / descriptions are searched in languages like SV or NL, even the strings of the specific funstion are not translated yet

In my expectation, the functions of the already translated titles and descriptions would always be findable, even if the search strings are not yet translated.

**Comment by S-Man42** [comment]
For the first step, it's important to have the searchstring files in Crowdin. It's got urgent quickly with all the fast incoming translations.

Althought you are right with the titles, it should not be part of this ticket as it is much more complicated to implement it. It must be faced furtherly but not in first step.

**Comment by Birdy2404** [comment]
I'm with you, but don't we add in the search string onyl the words, which are not in the title already? So I wouldn't find the function, if I know it's name?
So for me the second step should be prio 1. However I will split the ticket 😊

**Comment by S-Man42** [comment]
As soon as @ludoo0d0a prepared the files, you are free to add the titles to the searchstrings. i guess, it's the best way

**Comment by ludoo0d0a** [comment]
Thanks to crowdin cli, tasks (upload/download) are really easy (I wrote a readme). 
Not tested with intellij plugin, but should work the same.

searchstrings added in crowdin
descriptions translations downloaded

Note : please do not add multiple langs with same country code (china zh as sample)
for now, we don't support locale like zh_cn zh_tw. => i removed chinse traditional (chinese simplified is enough)

**Comment by ludoo0d0a** [comment]
searchstrings are in crowdin now.
@Birdy2404 : open a new ticket for the other issue (I didn't understand)
