### ISSUE TITLE
bug: Widerstand search string not vor all 3 types

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#897]
![2022-01-22 22_05_44-Window](https://user-images.githubusercontent.com/62543251/150655528-e78b5bef-bda7-4f58-8c93-2a1f1ba43ae3.png)
![2022-01-22 22_06_13-Window](https://user-images.githubusercontent.com/62543251/150655532-56b1a6eb-cdc8-4982-9ff8-024b00e1d976.png)

Bei der Suche kommt nur Widerstandsrechner & EIA-96-Codes aber nicht  Widerstandsfarbcode

**Comment by Birdy2404** [comment]
![grafik](https://user-images.githubusercontent.com/34218281/150693826-2af9ddfd-1194-4076-b706-17514ac59bd9.png)
Auf Crowdin in den Suchbegriffen gelöst
