### ISSUE TITLE
Coordinates in picture not found

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#912]
https://www.bauernhofurlaub-ruegen.de/wp-content/uploads/Komoran.jpg

This picture contains location data as the following screenshot from exif.regex.info shows:

![grafik](https://user-images.githubusercontent.com/16626063/152692434-f0824461-2ba9-43b3-a119-a50ac448a42c.png)

Our Exif tool doesn't show the location data.

Please check whether this is a bug or try to add new function to display XMP data.

**Comment by ludoo0d0a** [comment]
https://github.com/S-Man42/GCWizard/pull/913

**Comment by S-Man42** [comment]
Works for me. However following issues:

1. Date format for section "image" and "History" looks weird. In "History" it is ISO formatted, instead of expected German formatting and the "image" date looks like no format that I ever saw before. Could you please add proper Date Format (i believe you did this already for other section in Exif IIRC)

![grafik](https://user-images.githubusercontent.com/16626063/153876650-8956807e-1f3d-4361-9d65-eb9439fe604b.png)
![grafik](https://user-images.githubusercontent.com/16626063/153876659-7995e350-008b-4079-97cf-293b942a1b1f.png)


2. I believe it makes sense to but the GPS output right under the GPS section. I had this image:
https://github.com/ianare/exif-samples/blob/master/jpg/gps/DSCN0025.jpg?raw=true

And this one has many exif data. I believe the user would not scroll completely to the bottom to find the GPS Output...
![grafik](https://user-images.githubusercontent.com/16626063/153876633-ef87a7ae-40fd-46fe-8e2a-e2308a875537.png)

**Comment by ludoo0d0a** [comment]
There is no standard format for dates in xmp.i could try a parseAndGuess but it won't work everytime. That's why I let as text

**Comment by ludoo0d0a** [comment]
What do you suggest for gps widget location ?
Moving every time at a higher level ?
