### ISSUE TITLE
Symboltables: Puzzle Code: Better Encryption

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#915]
I really don't like the encryption of the Puzzle Code. It doesn't look like a complete puzzle, but only like a bunch of loose tiles...

![grafik](https://user-images.githubusercontent.com/16626063/152980273-a31edc2c-5a58-4e70-8726-12a3e38d490e.png)

I'd love to have a better encryption here:

The iOS tool GC Tools has a good approach on this. For encryption it doesn't use the complete puzzle shape but only the bottom and right side. And then put them together without any offset between the tiles.

<img src="https://user-images.githubusercontent.com/16626063/152985778-67525f43-6e3a-4ffc-b05e-715e34c7a028.jpg" width="200">
<img src="https://user-images.githubusercontent.com/16626063/152985790-5d9c6dc2-f5a3-4ee6-b7c2-5e52981d4f8d.jpg" width="200">

So, my approach would be to enhance the symbol table encryption this way:

1. add a new symbolset "xyz_encryption.zip" to the puzzle directory. Same as the normal one but without top and left side and without space around them
2. config file parameters:

```
{
...
"encryption": {
   "alternate_set": true,
   "borders": {
       "top": true,
       "left": true
   }
   "offset": 0
}
}
```
3. If "encryption.alternate_set found in config file, don't use the normal puzzle.zip but puzzle_encryption.zip. 
4. If "encryption.offset" found: Between rows and columns: Given offset
5. If "encryption.draw_borders.top" found: draw a line at the top with given offset to symbols.

Furtherly:

For example "Stippel Code": Originally the code is written in alternate directions: First row: Left to Right, Second row from right to left (with verically flipped symbols and without space inbetween). Gernreich doesn't follow a fixed direction; each following symbol starts where the previous one ended (A is from left bottom corner to right middle; B would start at right middle and goes down...). So many more options are imaginable. But let us start with that relative easy one...

**Comment by S-Man42** [comment]
@Birdy2404 

Could you please provide the image set? I guess it would be a good idea to make them transparent. So simply black; the bottom and right side. Just remove the top and the left...

**Comment by S-Man42** [comment]
GC Tools has these overlapping lines in the right bottom corner. There are very important, I currently realized. They must me as long as the convex/outer nubsies...
![grafik](https://user-images.githubusercontent.com/16626063/153183860-be9aabd3-a7a7-4df6-a721-54a25f5ce2d8.png)

**Comment by S-Man42** [comment]
I believe it makes sense to draw the symbols completely new because the current data has not a good resolution with lots of artifacts which could make the final result look very nasty...

**Comment by Birdy2404** [comment]
ftp://.../Exchange/Symboltabellen/puzzle
