### ISSUE TITLE
Malbolge tests failed

### ISSUE THREAD

**Issue by Mike-3** [S-Man42/GCWizard#924]
output from all malbolge test programs
-> common_programming_error_invalid_program

**Comment by t-m-z** [comment]
I will have a look on this.

I have just tested with Hello World from 
https://de.wikipedia.org/wiki/Malbolge
and everything was fine.

Sent from MailDroid

-----Original Message-----
From: Mike-3 ***@***.***>
To: S-Man42/GCWizard ***@***.***>
Cc: Subscribed ***@***.***>
Sent: So., 13 Feb. 2022 18:42
Subject: [S-Man42/GCWizard] Malbolge tests failed (Issue #924)

output from all malbolge test programs
-> common_programming_error_invalid_program

-- 
Reply to this email directly or view it on GitHub:
https://github.com/S-Man42/GCWizard/issues/924

**Comment by t-m-z** [comment]
the input data malformed due to missing escape sequences.
the algorithm is oky
