### ISSUE TITLE
Enhancements for the Unit-Tool - The Potrzebie system of weights and measures

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#927]
https://webmadness.net/blog/?post=knuth
https://www.webofstories.com/play/donald.knuth/8;jsessionid=7DAC6DB059237C2D113C8C6DA976714D
https://en.wikipedia.org/wiki/Potrzebie
https://www.primidi.com/potrzebie/system_of_measurement

**Comment by S-Man42** [comment]
:D

**Comment by t-m-z** [comment]
one thing is left: the calendar system   ;-)

**Comment by S-Man42** [comment]
Hm, does it make sense to convert you calenders tool into a unit? Then you could join the calender, the maya thing... etc..

**Comment by t-m-z** [comment]
something to consider.
however, the reference unit would be JulianDate and there is a need to incorporate methods instead of simple mathmatics.

I would stick to the calenderconverter tool for a first guess.

Sent from MailDroid

-----Original Message-----

**Comment by S-Man42** [comment]
Into. the engine of course you able to put in every method as callback, not only a + b... ;)
