### ISSUE TITLE
Upgrade flutter_map to 0.14

### ISSUE THREAD

**Issue by S-Man42** [S-Man42/GCWizard#989]
They added breaking changes. First tries fail because of no panmable markers anymore.

**Comment by Mike-3** [comment]
https://github.com/fleaflet/flutter_map/issues/1199

**Comment by Mike-3** [comment]
https://github.com/S-Man42/GCWizard/pull/981

archive: ^3.2.1 -> ^3.2.2

**Comment by S-Man42** [comment]
https://github.com/S-Man42/GCWizard/pull/992
