### ISSUE TITLE
Befunge - esoteric programming Language

### ISSUE THREAD

**Issue by t-m-z** [S-Man42/GCWizard#991]
https://en.wikipedia.org/wiki/Befunge

**Comment by S-Man42** [comment]
Befunge 2D is the really great challenge! :D

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/160240408-8f5d848d-2984-42b6-a803-4acb7cfc0424.png)

**Comment by t-m-z** [comment]
![image](https://user-images.githubusercontent.com/2946628/160240425-e35bb10e-1492-43a7-a0eb-5930a8a3c91a.png)
