### ISSUE TITLE
Bug? Eingeschlossene Flächen 

### ISSUE THREAD

**Issue by AndyPuma** [S-Man42/GCWizard#997]
![Screenshot_20220329-132718](https://user-images.githubusercontent.com/62543251/160665408-ab628d7a-e684-40c9-8c66-b7de1737ed34.png)
![Screenshot_20220329-133204](https://user-images.githubusercontent.com/62543251/160665493-13b5dde0-2c3f-4275-b930-0aade2a579de.png)
Wenn Sonderzeichen an der Zahlengruppe sind, ist die Zählung nicht korrekt.
Bsp.:  https://coord.info/GC89X0Q

**Comment by Mike-3** [comment]
Die Sonderzeichen sind nicht das Problem. Ein ° wird als eine Fläche gezählt. Aber es werden bis jetzt nur Leerzeichen als Block-Trenner genutzt. Deshalb werden die 2 Blöcke wo der Punkt dazwischen ist, nur als ein Block betrachtet.

**Comment by AndyPuma** [comment]
Ok

Mike-3 ***@***.***> schrieb am Fr., 1. Apr. 2022, 19:35:

**Comment by Mike-3** [comment]
Überlege gerade, ob man eine Anwahl der zu berücksichtigenden Zeichen rein machen sollte.
Zahlen 
Buchstaben
Sonderzeichen

**Comment by Mike-3** [comment]
![grafik](https://user-images.githubusercontent.com/70719484/161331402-5bc0e099-08cc-4f86-967e-7a263a27a343.png)
ok ?

**Comment by AndyPuma** [comment]
für mich ja :-)

Mike-3 ***@***.***> schrieb am Fr., 1. Apr. 2022, 21:45:
